apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - bank-db.yaml
  - bank-api.yaml
  - bank-frontend.yaml
labels:
  - pairs:
      r6.opencenter.dev/business-system: mockbank-mobile-banking
