#!/usr/bin/env bash
# Generated by OSPC→FLEX Deployer — do NOT edit by hand.
# Floating IP association is intentionally SKIPPED — assign manually after deploy.
set -uo pipefail

# ── Runtime config (override from environment before running) ──────────────
SERVER_WAIT_SEC="${SERVER_WAIT_SEC:-600}"       # 10 min per server active-wait
VOLUME_WAIT_SEC="${VOLUME_WAIT_SEC:-300}"       # 5 min per volume available-wait
LB_WAIT_SEC="${LB_WAIT_SEC:-480}"               # 8 min per LB active-wait
OS_CMD_TIMEOUT_SEC="${OS_CMD_TIMEOUT_SEC:-30}"  # 30s per API call — skip if exceeded
RESOURCE_COLLISION_POLICY="${RESOURCE_COLLISION_POLICY:-reuse}"
ROLLBACK_AUTO_APPROVE=1                          # never prompt; rollback always runs
ROLLBACK_SCRIPT_PATH="${ROLLBACK_SCRIPT_PATH:-/home/dzoan/OSPC2FLEX/osflex-deployer-fullmig-5.0.0420current/uploads/last_rollback_$(date +%Y%m%d_%H%M%S).sh}"
DEPLOY_ERRORS=0
DEPLOY_SKIPPED=0
DEPLOY_CREATED=0
DEPLOY_TIMEOUTS=0
_ROLLBACK_CMDS=()   # populated at runtime; only resources CREATED (not reused) are added

# ── Timestamped logging ──────────────────────────────────────────────────────
log()  { echo "[$(date '+%H:%M:%S')] $*"; }
warn() { echo "[$(date '+%H:%M:%S')] ⚠  $*" >&2; }
err()  { echo "[$(date '+%H:%M:%S')] ✖  $*" >&2; DEPLOY_ERRORS=$((DEPLOY_ERRORS+1)); }
ok()   { echo "[$(date '+%H:%M:%S')] ✔  $*"; DEPLOY_CREATED=$((DEPLOY_CREATED+1)); }
skip() { echo "[$(date '+%H:%M:%S')] ↩  $*"; DEPLOY_SKIPPED=$((DEPLOY_SKIPPED+1)); }

phase_banner() {
  local msg="$1"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  log "🚀  $msg"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# ── Guarded openstack wrapper ─────────────────────────────────────────────────
run_with_timeout() {
  local timeout_sec="$1"
  shift
  "$@" &
  local pid=$!
  local start_ts elapsed
  start_ts=$(date +%s)
  while kill -0 "$pid" 2>/dev/null; do
    elapsed=$(( $(date +%s) - start_ts ))
    if (( elapsed >= timeout_sec )); then
      warn "⏭  TIMEOUT ${timeout_sec}s — SKIPPING task and continuing deploy: $*"
      kill -TERM "$pid" 2>/dev/null || true; sleep 1
      kill -KILL "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
      DEPLOY_TIMEOUTS=$((DEPLOY_TIMEOUTS+1))
      return 0   # skip — do NOT block the rest of the deploy
    fi
    sleep 1
  done
  wait "$pid"
}

os() {
  log "+ openstack $*"
  run_with_timeout "$OS_CMD_TIMEOUT_SEC" openstack "$@"
}

# ── Resource idempotency ──────────────────────────────────────────────────────
resource_exists() {
  local kind="$1" name="$2"
  case "$kind" in
    network)       openstack network show "$name" >/dev/null 2>&1 ;;
    subnet)        openstack subnet show "$name" >/dev/null 2>&1 ;;
    router)        openstack router show "$name" >/dev/null 2>&1 ;;
    security_group) openstack security group show "$name" >/dev/null 2>&1 ;;
    instance)      openstack server show "$name" >/dev/null 2>&1 ;;
    volume)        openstack volume show "$name" >/dev/null 2>&1 ;;
    load_balancer) openstack loadbalancer show "$name" >/dev/null 2>&1 ;;
    listener)      openstack loadbalancer listener show "$name" >/dev/null 2>&1 ;;
    pool)          openstack loadbalancer pool show "$name" >/dev/null 2>&1 ;;
    *) return 1 ;;
  esac
}

create_or_reuse() {
  local kind="$1" name="$2"
  shift 2
  if resource_exists "$kind" "$name"; then
    if [[ "$RESOURCE_COLLISION_POLICY" == "fail" ]]; then
      err "BLOCKER: $kind '$name' already exists and RESOURCE_COLLISION_POLICY=fail"
      return 1
    fi
    skip "Already exists — reusing $kind: $name"
    return 0
  fi
  log "Creating $kind: $name ..."
  if "$@"; then
    ok "Created $kind: $name"
    _rollback_push "$kind" "$name"
  else
    err "FAILED to create $kind: $name — check output above for reason"
    if [[ "$kind" == "instance" ]]; then
      warn "  Common blockers for instances:"
      warn "    • Flavor disk too small for image (check 'minimum_disk' in image metadata)"
      warn "    • Quota exceeded (check 'openstack quota show')"
      warn "    • Network not reachable (check phase 1 succeeded)"
      warn "    • Key pair does not exist in project"
    fi
  fi
}

# ── Per-run rollback tracker (only NEW resources, not pre-existing ones) ─────
_rollback_push() {
  local kind="$1" name="$2" cmd
  case "$kind" in
    network)        cmd="openstack network delete \"$name\" || true" ;;
    subnet)         cmd="openstack subnet delete \"$name\" || true" ;;
    router)         cmd="openstack router remove subnet \"$name\" \"${SUBNET_NAME:-tenant-subnet}\" || true; openstack router unset --external-gateway \"$name\" || true; openstack router delete \"$name\" || true" ;;
    security_group) cmd="openstack security group delete \"$name\" || true" ;;
    instance)       cmd="openstack server delete --wait \"$name\" 2>/dev/null || openstack server delete \"$name\" || true" ;;
    volume)         cmd="openstack volume delete --force \"$name\" || true" ;;
    load_balancer)  cmd="openstack loadbalancer delete --cascade \"$name\" 2>/dev/null || openstack loadbalancer delete \"$name\" || true" ;;
    listener|pool)  return 0 ;;
    *)              return 0 ;;
  esac
  _ROLLBACK_CMDS=("$cmd" "${_ROLLBACK_CMDS[@]+${_ROLLBACK_CMDS[@]}}")
}

_finalize_rollback() {
  [[ ${#_ROLLBACK_CMDS[@]} -eq 0 ]] && { warn "No new resources created — rollback script skipped."; return 0; }
  local n=${#_ROLLBACK_CMDS[@]} i
  {
    echo '#!/usr/bin/env bash'
    echo '# AUTO-GENERATED rollback — deletes ONLY resources created in THIS run.'
    echo '# Pre-existing (reused) resources are NOT touched.'
    echo 'set -uo pipefail'
    echo 'ROLLBACK_AUTO_APPROVE=1'
    echo 'log() { echo "[$(date +%H:%M:%S)] $*"; }'
    printf "log \"Starting rollback: $n step(s) in reverse creation order\"\n"
    for (( i=0; i<n; i++ )); do
      printf "log \"  [%d/%d] %s\"\n" "$((i+1))" "$n" "${_ROLLBACK_CMDS[$i]}"
      printf "%s\n" "${_ROLLBACK_CMDS[$i]}"
    done
    echo 'log "✅  Rollback complete."'
  } > "$ROLLBACK_SCRIPT_PATH"
  chmod +x "$ROLLBACK_SCRIPT_PATH"
  log "↩  Rollback script written: $ROLLBACK_SCRIPT_PATH ($n steps)"
}

# ── Wait helpers (with live progress output) ──────────────────────────────────
wait_for_server_active() {
  local name="$1"
  local max_sec="${2:-$SERVER_WAIT_SEC}"
  local sleep_sec=10
  local elapsed=0 status fault
  log "⏳ Waiting for server '$name' to become ACTIVE (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack server show "$name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "ACTIVE" ]]; then
      ok "Server '$name' is ACTIVE (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "ERROR" ]]; then
      fault=$(openstack server show "$name" -f value -c fault 2>/dev/null || echo "unknown fault")
      err "BLOCKER: Server '$name' entered ERROR state after ${elapsed}s"
      err "  Fault details: $fault"
      warn "  Common causes:"
      warn "    • Flavor disk smaller than image minimum_disk — use --boot-from-volume"
      warn "    • Host capacity insufficient — try a different availability zone"
      warn "    • Image not found or inaccessible in this region"
      warn "  NEXT STEP: Delete the error server and re-create with a larger flavor or boot-from-volume"
      return 1
    fi
    log "  ... server '$name' status=$status  elapsed=${elapsed}s / ${max_sec}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Server '$name' did not reach ACTIVE after ${max_sec}s (last status: $status)"
  warn "  NEXT STEP: Check 'openstack server show $name' — if still BUILD, try waiting longer"
  warn "            If ERROR, see fault reason above and re-create with corrected params"
  return 1
}

wait_for_volume_available() {
  local name="$1"
  local max_sec="${2:-$VOLUME_WAIT_SEC}"
  local sleep_sec=5
  local elapsed=0 status
  log "⏳ Waiting for volume '$name' to become available (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack volume show "$name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "available" ]]; then
      ok "Volume '$name' is available (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "error" ]]; then
      err "BLOCKER: Volume '$name' entered error state after ${elapsed}s"
      warn "  NEXT STEP: Delete the volume and re-create, or check Cinder quota"
      return 1
    fi
    log "  ... volume '$name' status=$status  elapsed=${elapsed}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Volume '$name' not available after ${max_sec}s"
  return 1
}

volume_status() {
  local name="$1"
  openstack volume show "$name" -f value -c status 2>/dev/null || true
}

server_has_volume() {
  local server_name="$1" volume_name="$2" volume_id
  volume_id=$(openstack volume show "$volume_name" -f value -c id 2>/dev/null || true)
  [[ -n "$volume_id" ]] && openstack server volume list "$server_name" -f value -c ID 2>/dev/null | grep -Fx "$volume_id" >/dev/null 2>&1
}

# -- Volume-attach with fast retry/skip (no 600s block) --
# Usage: _vol_attach_with_retry <server_name> <volume_name> [max_trials]
# Skips gracefully after max_trials instead of blocking forever.
_vol_attach_with_retry() {
  local inst_name="$1" vol_name="$2"
  local max_trials="${3:-${MAX_VOL_ATTACH_TRIALS:-3}}"
  local attempt=0 srv_status vol_status
  while (( attempt < max_trials )); do
    attempt=$(( attempt + 1 ))
    srv_status=$(openstack server show "$inst_name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$srv_status" != "ACTIVE" ]]; then
      warn "  [Vol Attach] $inst_name is $srv_status -- trial $attempt/$max_trials"
      if (( attempt >= max_trials )); then
        warn "  [Vol Attach] SKIP: $inst_name never became ACTIVE after $max_trials trials -- attach $vol_name manually"
        (( DEPLOY_ERRORS++ )) || true; return 1
      fi
      sleep 15; continue
    fi
    if server_has_volume "$inst_name" "$vol_name"; then
      ok "Volume $vol_name already attached to $inst_name; skipping."; return 0
    fi
    vol_status=$(openstack volume show "$vol_name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$vol_status" == "in-use" ]]; then
      warn "  [Vol Attach] Volume $vol_name is in-use (not attached to $inst_name); skipping."; return 1
    fi
    if [[ "$vol_status" != "available" ]]; then
      warn "  [Vol Attach] Volume $vol_name is $vol_status -- trial $attempt/$max_trials"
      if (( attempt >= max_trials )); then
        warn "  [Vol Attach] SKIP: volume $vol_name not available after $max_trials trials -- attach manually"
        (( DEPLOY_ERRORS++ )) || true; return 1
      fi
      sleep 15; continue
    fi
    if openstack server add volume "$inst_name" "$vol_name" 2>/dev/null; then
      ok "✅ Volume '$vol_name' attached to '$inst_name' (trial $attempt)"; return 0
    fi
    warn "  [Vol Attach] Attach command failed — trial $attempt/$max_trials (retrying in 10s)"
    sleep 10
  done
  warn "  [Vol Attach] ⏭ SKIP: '$vol_name' → '$inst_name' after $max_trials failed trials — attach manually"
  (( DEPLOY_ERRORS++ )) || true; return 1
}

wait_for_loadbalancer_active() {
  local name="$1"
  local max_sec="${2:-$LB_WAIT_SEC}"
  local sleep_sec=10
  local elapsed=0 status
  log "⏳ Waiting for load balancer '$name' to become ACTIVE (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack loadbalancer show "$name" -f value -c provisioning_status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "ACTIVE" ]]; then
      ok "Load balancer '$name' is ACTIVE (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "ERROR" ]]; then
      err "BLOCKER: Load balancer '$name' provisioning ERROR after ${elapsed}s"
      warn "  NEXT STEP: 'openstack loadbalancer show $name' for operating_status details"
      return 1
    fi
    log "  ... LB '$name' provisioning_status=$status  elapsed=${elapsed}s / ${max_sec}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Load balancer '$name' did not reach ACTIVE after ${max_sec}s"
  return 1
}

subnet_id_from_name() {
  openstack subnet show "$1" -f value -c id 2>/dev/null || true
}

instance_ip_on_network() {
  local server_name="$1" network_name="$2" ports_line ip line
  ports_line=$(openstack port list --server "$server_name" --network "$network_name" -f value -c "Fixed IP Addresses" 2>/dev/null | head -n 1 || true)
  if [[ -n "$ports_line" ]]; then
    ip=$(echo "$ports_line" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1 || true)
    [[ -n "$ip" ]] && { echo "$ip"; return 0; }
  fi
  line=$(openstack server show "$server_name" -f value -c addresses 2>/dev/null | tr "," "\n" | sed "s/^ *//g" | grep "^${network_name}=" | head -n 1 || true)
  [[ -z "$line" ]] && return 0
  ip=$(echo "$line" | sed -E 's/^[^=]+=([0-9.]+).*/\1/g')
  echo "$ip"
}

wait_for_instance_ip_on_network() {
  local server_name="$1" network_name="$2"
  local max_sec="${3:-120}" sleep_sec=5
  local elapsed=0 ip
  log "⏳ Waiting for IP on network '$network_name' for server '$server_name' ..."
  while (( elapsed < max_sec )); do
    ip=$(instance_ip_on_network "$server_name" "$network_name")
    if [[ -n "$ip" ]]; then
      log "  IP resolved: $server_name → $ip"
      echo "$ip"; return 0
    fi
    sleep "$sleep_sec"; elapsed=$((elapsed + sleep_sec))
  done
  warn "Could not resolve IP for $server_name on $network_name after ${max_sec}s"
  return 1
}

pool_has_member_ip() {
  openstack loadbalancer member list "$1" -f value -c address 2>/dev/null | grep -Fx "$2" >/dev/null 2>&1
}

loadbalancer_vip_port_id() {
  openstack loadbalancer show "$1" -f value -c vip_port_id 2>/dev/null || true
}

# NOTE: Floating IP helpers kept for reference but are NOT called by this script.
# Floating IPs are assigned MANUALLY after deployment completes.
server_has_floating_ip() {
  local out; out=$(openstack floating ip list --server "$1" -f value -c "Floating IP Address" 2>/dev/null || true)
  [[ -n "$(echo "$out" | tr -d "[:space:]")" ]]
}

port_has_floating_ip() {
  local out; out=$(openstack floating ip list --port "$1" -f value -c "Floating IP Address" 2>/dev/null || true)
  [[ -n "$(echo "$out" | tr -d "[:space:]")" ]]
}

log "Deploy script started at $(date)"
log "Floating IP assignment: SKIPPED (assign manually via Horizon or CLI after deploy)"
log "Server wait timeout   : ${SERVER_WAIT_SEC}s"
log "LB wait timeout       : ${LB_WAIT_SEC}s"
log "Collision policy      : ${RESOURCE_COLLISION_POLICY}"

phase_banner "PHASE 1: Networking Foundation — networks, subnets, routers, security groups" "PHASE 2: LB Scaffold will start next"
create_or_reuse network tenant-net os network create tenant-net
create_or_reuse network PUBLICNET os network create PUBLICNET
create_or_reuse subnet tenant-subnet os subnet create --network tenant-net --subnet-range 10.60.0.0/24 tenant-subnet
create_or_reuse router tenant-router os router create tenant-router
os router set --external-gateway PUBLICNET tenant-router
os router add subnet tenant-router tenant-subnet || true
create_or_reuse security_group default os security group create default
phase_banner "PHASE 2: LB Scaffold — LB + Listener + Pool (Octavia Amphora provisioning in parallel with VM boot)" "PHASE 3: Volume Creation next"
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -z "$lb_subnet_id" ]]; then
  echo "Skipping load balancer frontend- Load-Balancer-01: subnet tenant-subnet not found." >&2
else
  create_or_reuse load_balancer 'frontend- Load-Balancer-01' os loadbalancer create --name 'frontend- Load-Balancer-01' --provider ovn --vip-subnet-id "$lb_subnet_id"
  wait_for_loadbalancer_active 'frontend- Load-Balancer-01'
  create_or_reuse listener 'frontend- Load-Balancer-01-listener' os loadbalancer listener create --name 'frontend- Load-Balancer-01-listener' --protocol HTTP --protocol-port 80 'frontend- Load-Balancer-01'
  wait_for_loadbalancer_active 'frontend- Load-Balancer-01'
  create_or_reuse pool 'frontend- Load-Balancer-01-pool' os loadbalancer pool create --name 'frontend- Load-Balancer-01-pool' --lb-algorithm ROUND_ROBIN --listener 'frontend- Load-Balancer-01-listener' --protocol HTTP
  wait_for_loadbalancer_active 'frontend- Load-Balancer-01'
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -z "$lb_subnet_id" ]]; then
  echo "Skipping load balancer u24backend: subnet tenant-subnet not found." >&2
else
  create_or_reuse load_balancer u24backend os loadbalancer create --name u24backend --provider ovn --vip-subnet-id "$lb_subnet_id"
  wait_for_loadbalancer_active u24backend
  create_or_reuse listener u24backend-listener os loadbalancer listener create --name u24backend-listener --protocol HTTP --protocol-port 80 u24backend
  wait_for_loadbalancer_active u24backend
  create_or_reuse pool u24backend-pool os loadbalancer pool create --name u24backend-pool --lb-algorithm ROUND_ROBIN --listener u24backend-listener --protocol HTTP
  wait_for_loadbalancer_active u24backend
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -z "$lb_subnet_id" ]]; then
  echo "Skipping load balancer DB_loadbalancer MYSQL: subnet tenant-subnet not found." >&2
else
  create_or_reuse load_balancer 'DB_loadbalancer MYSQL' os loadbalancer create --name 'DB_loadbalancer MYSQL' --provider ovn --vip-subnet-id "$lb_subnet_id"
  wait_for_loadbalancer_active 'DB_loadbalancer MYSQL'
  create_or_reuse listener 'DB_loadbalancer MYSQL-listener' os loadbalancer listener create --name 'DB_loadbalancer MYSQL-listener' --protocol HTTP --protocol-port 80 'DB_loadbalancer MYSQL'
  wait_for_loadbalancer_active 'DB_loadbalancer MYSQL'
  create_or_reuse pool 'DB_loadbalancer MYSQL-pool' os loadbalancer pool create --name 'DB_loadbalancer MYSQL-pool' --lb-algorithm ROUND_ROBIN --listener 'DB_loadbalancer MYSQL-listener' --protocol HTTP
  wait_for_loadbalancer_active 'DB_loadbalancer MYSQL'
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -z "$lb_subnet_id" ]]; then
  echo "Skipping load balancer LBmariaDB: subnet tenant-subnet not found." >&2
else
  create_or_reuse load_balancer LBmariaDB os loadbalancer create --name LBmariaDB --provider ovn --vip-subnet-id "$lb_subnet_id"
  wait_for_loadbalancer_active LBmariaDB
  create_or_reuse listener LBmariaDB-listener os loadbalancer listener create --name LBmariaDB-listener --protocol HTTP --protocol-port 80 LBmariaDB
  wait_for_loadbalancer_active LBmariaDB
  create_or_reuse pool LBmariaDB-pool os loadbalancer pool create --name LBmariaDB-pool --lb-algorithm ROUND_ROBIN --listener LBmariaDB-listener --protocol HTTP
  wait_for_loadbalancer_active LBmariaDB
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -z "$lb_subnet_id" ]]; then
  echo "Skipping load balancer perconaLB: subnet tenant-subnet not found." >&2
else
  create_or_reuse load_balancer perconaLB os loadbalancer create --name perconaLB --provider ovn --vip-subnet-id "$lb_subnet_id"
  wait_for_loadbalancer_active perconaLB
  create_or_reuse listener perconaLB-listener os loadbalancer listener create --name perconaLB-listener --protocol HTTP --protocol-port 80 perconaLB
  wait_for_loadbalancer_active perconaLB
  create_or_reuse pool perconaLB-pool os loadbalancer pool create --name perconaLB-pool --lb-algorithm ROUND_ROBIN --listener perconaLB-listener --protocol HTTP
  wait_for_loadbalancer_active perconaLB
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -z "$lb_subnet_id" ]]; then
  echo "Skipping load balancer dblb: subnet tenant-subnet not found." >&2
else
  create_or_reuse load_balancer dblb os loadbalancer create --name dblb --provider ovn --vip-subnet-id "$lb_subnet_id"
  wait_for_loadbalancer_active dblb
  create_or_reuse listener dblb-listener os loadbalancer listener create --name dblb-listener --protocol HTTP --protocol-port 80 dblb
  wait_for_loadbalancer_active dblb
  create_or_reuse pool dblb-pool os loadbalancer pool create --name dblb-pool --lb-algorithm ROUND_ROBIN --listener dblb-listener --protocol HTTP
  wait_for_loadbalancer_active dblb
fi
phase_banner "PHASE 3: Volume Creation — pre-provision block storage (Cinder is fast, do it early)" "PHASE 4: Compute launch next"
phase_banner "PHASE 4: Compute & DB Creation — Windows VMs fired in background first (sysprep is slow), Linux VMs and DB servers inline" "PHASE 5: LB Creation next"
echo "  -> Firing Windows VMs in background (sysprep takes longest)..."
_WIN_PIDS=()
( # Windows VM: Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-final-virtio
create_or_reuse instance Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-final-virtio os server create --flavor gp.0.4.4 --image Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-virtio-ready-img --network tenant-net --security-group default --password rAPDyNoQUfXOKo Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-final-virtio
) &
_WIN_PIDS+=($!)
( # Windows VM: Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide
create_or_reuse instance Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide os server create --flavor gp.0.4.4 --image Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide-img --network tenant-net --security-group default --password tfwMrbJkw0m774 Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide
) &
_WIN_PIDS+=($!)
( # Windows VM: windows2016opsc-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-final-virtio
create_or_reuse instance windows2016opsc-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-final-virtio os server create --flavor gp.0.4.4 --image windows2016opsc-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-virtio-ready-img --network tenant-net --security-group default --password Rk60MCL1iexlMP windows2016opsc-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-final-virtio
) &
_WIN_PIDS+=($!)
( # Windows VM: windows2016opsc-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide
create_or_reuse instance windows2016opsc-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide os server create --flavor gp.0.4.4 --image windows2016opsc-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide-img --network tenant-net --security-group default --password 02qivqUlYRoB1k windows2016opsc-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide
) &
_WIN_PIDS+=($!)
( # Windows VM: Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-snapwin-final-virtio
create_or_reuse instance Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-snapwin-final-virtio os server create --flavor gp.0.4.4 --image Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-snapwin-virtio-ready-img --network tenant-net --security-group default --password dzQcx8xKdHBq8a Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-snapwin-final-virtio
) &
_WIN_PIDS+=($!)
echo "  -> Provisioning Linux VMs..."
create_or_reuse instance opscwin2016-20260509-150218-snap-202605091502-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-final-virtio os server create --flavor gp.0.4.4 --image opscwin2016-20260509-150218-snap-202605091502-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-virtio-ready-img --network tenant-net --security-group default --key-name laptopubuntu24 opscwin2016-20260509-150218-snap-202605091502-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-final-virtio
create_or_reuse instance opscwin2016-20260509-150218-snap-202605091502-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide os server create --flavor gp.0.4.4 --image opscwin2016-20260509-150218-snap-202605091502-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide-img --network tenant-net --security-group default --key-name laptopubuntu24 opscwin2016-20260509-150218-snap-202605091502-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide
create_or_reuse instance ospc2flex-u22-20260428-0612-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780403571303906911-795ebdfd-37f3b5b6-c53 os server create --flavor gp.0.4.4 --image ospc2flex-u22-20260428-0612-r3-f2f-DFW3-to-IAD3-r3-f2f-DFW3-to-IAD3-r3-f2f-1780403571303906911-795ebdfd-37f3b5b6-c53 --network tenant-net --security-group default --key-name laptopubuntu24 ospc2flex-u22-20260428-0612-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780403571303906911-795ebdfd-37f3b5b6-c53
create_or_reuse instance ospc2flex-debian11new-20260425-2030-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780403571348846628-0bde8b56-80bd78d8-79b os server create --flavor gp.0.4.4 --image ospc2flex-debian11new-20260425-2030-r3-f2f-DFW3-to-IAD3-r3-f2f-DFW3-to-IAD3-r3-f2f-1780403571348846628-0bde8b56-80bd78d8-79b --network tenant-net --security-group default --key-name laptopubuntu24 ospc2flex-debian11new-20260425-2030-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780403571348846628-0bde8b56-80bd78d8-79b
create_or_reuse instance ospc2flex-debian11new-20260425-2030-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780392500355008154-de118600-80bd78d8-79b os server create --flavor gp.0.4.4 --image ospc2flex-debian11new-20260425-2030-r3-f2f-DFW3-to-IAD3-r3-f2f-DFW3-to-IAD3-r3-f2f-1780392500355008154-de118600-80bd78d8-79b --network tenant-net --security-group default --key-name laptopubuntu24 ospc2flex-debian11new-20260425-2030-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780392500355008154-de118600-80bd78d8-79b
create_or_reuse instance ospc2flex-u22-20260428-0612-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780390536201904367-9e0540ca-37f3b5b6-c53 os server create --flavor gp.0.4.4 --image ospc2flex-u22-20260428-0612-r3-f2f-DFW3-to-IAD3-r3-f2f-DFW3-to-IAD3-r3-f2f-1780390536201904367-9e0540ca-37f3b5b6-c53 --network tenant-net --security-group default --key-name laptopubuntu24 ospc2flex-u22-20260428-0612-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780390536201904367-9e0540ca-37f3b5b6-c53
create_or_reuse instance ospc2flex-u22-20260428-0612-r3-f2f-IAD3-to-DFW3-r3-f2f-1780287464918452382-8e4dcd88-34b04475-eb9-r3-f2f-IAD3-r3-f2f-1780364728120145934-360b13bd-37f3b5b6-c53 os server create --flavor gp.0.4.4 --image ospc2flex-u22-20260428-0612-r3-f2f-IAD3-to-DFW3-r3-f2f-1780287464918452382-8e4dcd88-34b04475-eb9-r3-f2f-DFW3-to-IAD3-r3-f2f-1780364728120145934-360b13bd-37f3b5b6-c53 --network tenant-net --security-group default --key-name laptopubuntu24 ospc2flex-u22-20260428-0612-r3-f2f-IAD3-to-DFW3-r3-f2f-1780287464918452382-8e4dcd88-34b04475-eb9-r3-f2f-IAD3-r3-f2f-1780364728120145934-360b13bd-37f3b5b6-c53
create_or_reuse instance ospc2flex-u22-20260428-0612-r3-f2f-IAD3-to-DFW3-r3-f2f-1780237311943674304-01d6d5a6-34b04475-eb9-r3-f2f-IAD3-r3-f2f-1780358850441571462-8614c3a9-794ff290-229 os server create --flavor gp.0.4.4 --image ospc2flex-u22-20260428-0612-r3-f2f-IAD3-to-DFW3-r3-f2f-1780237311943674304-01d6d5a6-34b04475-eb9-r3-f2f-DFW3-to-IAD3-r3-f2f-1780358850441571462-8614c3a9-794ff290-229 --network tenant-net --security-group default --key-name laptopubuntu24 ospc2flex-u22-20260428-0612-r3-f2f-IAD3-to-DFW3-r3-f2f-1780237311943674304-01d6d5a6-34b04475-eb9-r3-f2f-IAD3-r3-f2f-1780358850441571462-8614c3a9-794ff290-229
create_or_reuse instance ospc2flex-centos7-20260426-0733-r3-f2f-IAD3-r3-f2f-1780358850483093621-1266e8b4-35cd4a1f-66a os server create --flavor gp.0.4.4 --image ospc2flex-centos7-20260426-0733-r3-f2f-DFW3-to-IAD3-r3-f2f-1780358850483093621-1266e8b4-35cd4a1f-66a --network tenant-net --security-group default --key-name laptopubuntu24 ospc2flex-centos7-20260426-0733-r3-f2f-IAD3-r3-f2f-1780358850483093621-1266e8b4-35cd4a1f-66a
create_or_reuse instance dbian10new-flex-r3-f2f-IAD3-to-DFW3-r3-f2f-1780287464896372082-d00f1481-c92f855a-9cd-r3-f2f-IAD3-r3-f2f-1780312009852198659-1d53bcbe-a0ad6dbf-9a6 os server create --flavor gp.0.4.4 --image dbian10new-flex-r3-f2f-IAD3-to-DFW3-r3-f2f-1780287464896372082-d00f1481-c92f855a-9cd-r3-f2f-DFW3-to-IAD3-r3-f2f-1780312009852198659-1d53bcbe-a0ad6dbf-9a6 --network tenant-net --security-group default --key-name laptopubuntu24 dbian10new-flex-r3-f2f-IAD3-to-DFW3-r3-f2f-1780287464896372082-d00f1481-c92f855a-9cd-r3-f2f-IAD3-r3-f2f-1780312009852198659-1d53bcbe-a0ad6dbf-9a6
create_or_reuse instance IADjumphostu24 os server create --flavor gp.0.4.16 --image 'N/A (booted from volume)' --network tenant-net --security-group default --key-name laptopubuntu24 IADjumphostu24
echo "  -> Waiting for Windows VMs to finish provisioning..."
for _wpid in "${_WIN_PIDS[@]}"; do wait "$_wpid" || true; done
echo "  -> All Windows VMs provisioning complete."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "⚠  FLOATING IP ASSIGNMENT: SKIPPED (manual action required)"
log "   Assign Floating IPs manually via Horizon or CLI after deploy:"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-final-virtio <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip windows2016opsc-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-final-virtio <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip windows2016opsc-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip Windows_Server_2019Re-snap-20260416211842-snapwin-safe-ide-img-snapwin-safe-ide-img-snapwin-final-virtio <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip opscwin2016-20260509-150218-snap-202605091502-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-final-virtio <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip opscwin2016-20260509-150218-snap-202605091502-snapwin-virtio-ready-img-snapwin-safe-ide-img-r3-f2f-DFW3-to-IAD3-snapwin-safe-ide <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip ospc2flex-u22-20260428-0612-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780403571303906911-795ebdfd-37f3b5b6-c53 <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip ospc2flex-debian11new-20260425-2030-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780403571348846628-0bde8b56-80bd78d8-79b <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip ospc2flex-debian11new-20260425-2030-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780392500355008154-de118600-80bd78d8-79b <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip ospc2flex-u22-20260428-0612-r3-f2f-DFW3-to-IAD3-r3-f2f-IAD3-r3-f2f-1780390536201904367-9e0540ca-37f3b5b6-c53 <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip ospc2flex-u22-20260428-0612-r3-f2f-IAD3-to-DFW3-r3-f2f-1780287464918452382-8e4dcd88-34b04475-eb9-r3-f2f-IAD3-r3-f2f-1780364728120145934-360b13bd-37f3b5b6-c53 <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip ospc2flex-u22-20260428-0612-r3-f2f-IAD3-to-DFW3-r3-f2f-1780237311943674304-01d6d5a6-34b04475-eb9-r3-f2f-IAD3-r3-f2f-1780358850441571462-8614c3a9-794ff290-229 <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip ospc2flex-centos7-20260426-0733-r3-f2f-IAD3-r3-f2f-1780358850483093621-1266e8b4-35cd4a1f-66a <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip dbian10new-flex-r3-f2f-IAD3-to-DFW3-r3-f2f-1780287464896372082-d00f1481-c92f855a-9cd-r3-f2f-IAD3-r3-f2f-1780312009852198659-1d53bcbe-a0ad6dbf-9a6 <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip IADjumphostu24 <FIP>"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
phase_banner "PHASE 5: Load Balancer Creation — copies LB/Listener/Pool config from OSPC and wires server IPs as pool members (floating IPs not required)" "PHASE 6: Volume Attach next"
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -n "$lb_subnet_id" ]]; then
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -n "$lb_subnet_id" ]]; then
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -n "$lb_subnet_id" ]]; then
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -n "$lb_subnet_id" ]]; then
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -n "$lb_subnet_id" ]]; then
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -n "$lb_subnet_id" ]]; then
fi
phase_banner "PHASE 6: Volume Attachment — optional; skips automatically after ${MAX_VOL_ATTACH_TRIALS:-3} failed trials per pair"
MAX_VOL_ATTACH_TRIALS=${MAX_VOL_ATTACH_TRIALS:-3}  # override: MAX_VOL_ATTACH_TRIALS=5 bash <script>

# Write per-run rollback script before summary
_finalize_rollback

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "✅  DEPLOY COMPLETE at $(date)"
log "   Resources created  : $DEPLOY_CREATED"
log "   Resources skipped  : $DEPLOY_SKIPPED (already existed)"
log "   Tasks timed out    : $DEPLOY_TIMEOUTS (skipped after 30s — re-run or handle manually)"
log "   Errors encountered : $DEPLOY_ERRORS"
if (( DEPLOY_TIMEOUTS > 0 )); then
  warn "  ⏭  $DEPLOY_TIMEOUTS task(s) exceeded the 30s timeout and were skipped"
  warn "     Override limit:  OS_CMD_TIMEOUT_SEC=120 bash <script>"
  warn "     Re-run specific phases by setting RESOURCE_COLLISION_POLICY=reuse"
fi
log ""
log "NEXT STEPS (manual)"
log "  1. Assign Floating IPs to VMs and LB VIPs via Horizon or:"
log "       openstack floating ip create PUBLICNET"
log "       openstack server add floating ip <server> <fip>"
log "  2. Verify instances: openstack server list"
log "  3. Verify LBs:       openstack loadbalancer list"
log "  4. Verify volumes:   openstack volume list"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
