#!/usr/bin/env bash
# Generated by OSPC→FLEX Deployer — do NOT edit by hand.
# Floating IP association is intentionally SKIPPED — assign manually after deploy.
set -uo pipefail

# ── Runtime config (override from environment before running) ──────────────
SERVER_WAIT_SEC="${SERVER_WAIT_SEC:-600}"     # 10 min per server
VOLUME_WAIT_SEC="${VOLUME_WAIT_SEC:-300}"     # 5 min per volume
LB_WAIT_SEC="${LB_WAIT_SEC:-480}"             # 8 min per LB
OS_CMD_TIMEOUT_SEC="${OS_CMD_TIMEOUT_SEC:-120}" # 2 min per API call
RESOURCE_COLLISION_POLICY="${RESOURCE_COLLISION_POLICY:-reuse}"
DEPLOY_ERRORS=0
DEPLOY_SKIPPED=0
DEPLOY_CREATED=0

# ── Timestamped logging ──────────────────────────────────────────────────────
log()  { echo "[$(date '+%H:%M:%S')] $*"; }
warn() { echo "[$(date '+%H:%M:%S')] ⚠  $*" >&2; }
err()  { echo "[$(date '+%H:%M:%S')] ✖  $*" >&2; DEPLOY_ERRORS=$((DEPLOY_ERRORS+1)); }
ok()   { echo "[$(date '+%H:%M:%S')] ✔  $*"; DEPLOY_CREATED=$((DEPLOY_CREATED+1)); }
skip() { echo "[$(date '+%H:%M:%S')] ↩  $*"; DEPLOY_SKIPPED=$((DEPLOY_SKIPPED+1)); }

phase_banner() {
  local msg="$1"
  local next="${2:-}"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  log "🚀  $msg"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  if [[ -n "$next" ]]; then
    log "   NEXT STEP: $next"
  fi
}

# ── Guarded openstack wrapper ─────────────────────────────────────────────────
run_with_timeout() {
  local timeout_sec="$1"
  shift
  "$@" &
  local pid=$!
  local start_ts elapsed
  start_ts=$(date +%s)
  while kill -0 "$pid" 2>/dev/null; do
    elapsed=$(( $(date +%s) - start_ts ))
    if (( elapsed >= timeout_sec )); then
      warn "API call timed out after ${timeout_sec}s — killing: $*"
      kill -TERM "$pid" 2>/dev/null || true; sleep 2
      kill -KILL "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
      return 124
    fi
    sleep 1
  done
  wait "$pid"
}

os() {
  log "+ openstack $*"
  run_with_timeout "$OS_CMD_TIMEOUT_SEC" openstack "$@"
}

# ── Resource idempotency ──────────────────────────────────────────────────────
resource_exists() {
  local kind="$1" name="$2"
  case "$kind" in
    network)       openstack network show "$name" >/dev/null 2>&1 ;;
    subnet)        openstack subnet show "$name" >/dev/null 2>&1 ;;
    router)        openstack router show "$name" >/dev/null 2>&1 ;;
    security_group) openstack security group show "$name" >/dev/null 2>&1 ;;
    instance)      openstack server show "$name" >/dev/null 2>&1 ;;
    volume)        openstack volume show "$name" >/dev/null 2>&1 ;;
    load_balancer) openstack loadbalancer show "$name" >/dev/null 2>&1 ;;
    listener)      openstack loadbalancer listener show "$name" >/dev/null 2>&1 ;;
    pool)          openstack loadbalancer pool show "$name" >/dev/null 2>&1 ;;
    *) return 1 ;;
  esac
}

create_or_reuse() {
  local kind="$1" name="$2"
  shift 2
  if resource_exists "$kind" "$name"; then
    if [[ "$RESOURCE_COLLISION_POLICY" == "fail" ]]; then
      err "BLOCKER: $kind '$name' already exists and RESOURCE_COLLISION_POLICY=fail"
      return 1
    fi
    skip "Already exists — reusing $kind: $name"
    return 0
  fi
  log "Creating $kind: $name ..."
  if "$@"; then
    ok "Created $kind: $name"
  else
    err "FAILED to create $kind: $name — check output above for reason"
    if [[ "$kind" == "instance" ]]; then
      warn "  Common blockers for instances:"
      warn "    • Flavor disk too small for image (check 'minimum_disk' in image metadata)"
      warn "    • Quota exceeded (check 'openstack quota show')"
      warn "    • Network not reachable (check phase 1 succeeded)"
      warn "    • Key pair does not exist in project"
    fi
  fi
}

# ── Wait helpers (with live progress output) ──────────────────────────────────
wait_for_server_active() {
  local name="$1"
  local max_sec="${2:-$SERVER_WAIT_SEC}"
  local sleep_sec=10
  local elapsed=0 status fault
  log "⏳ Waiting for server '$name' to become ACTIVE (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack server show "$name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "ACTIVE" ]]; then
      ok "Server '$name' is ACTIVE (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "ERROR" ]]; then
      fault=$(openstack server show "$name" -f value -c fault 2>/dev/null || echo "unknown fault")
      err "BLOCKER: Server '$name' entered ERROR state after ${elapsed}s"
      err "  Fault details: $fault"
      warn "  Common causes:"
      warn "    • Flavor disk smaller than image minimum_disk — use --boot-from-volume"
      warn "    • Host capacity insufficient — try a different availability zone"
      warn "    • Image not found or inaccessible in this region"
      warn "  NEXT STEP: Delete the error server and re-create with a larger flavor or boot-from-volume"
      return 1
    fi
    log "  ... server '$name' status=$status  elapsed=${elapsed}s / ${max_sec}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Server '$name' did not reach ACTIVE after ${max_sec}s (last status: $status)"
  warn "  NEXT STEP: Check 'openstack server show $name' — if still BUILD, try waiting longer"
  warn "            If ERROR, see fault reason above and re-create with corrected params"
  return 1
}

wait_for_volume_available() {
  local name="$1"
  local max_sec="${2:-$VOLUME_WAIT_SEC}"
  local sleep_sec=5
  local elapsed=0 status
  log "⏳ Waiting for volume '$name' to become available (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack volume show "$name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "available" ]]; then
      ok "Volume '$name' is available (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "error" ]]; then
      err "BLOCKER: Volume '$name' entered error state after ${elapsed}s"
      warn "  NEXT STEP: Delete the volume and re-create, or check Cinder quota"
      return 1
    fi
    log "  ... volume '$name' status=$status  elapsed=${elapsed}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Volume '$name' not available after ${max_sec}s"
  return 1
}

volume_status() {
  local name="$1"
  openstack volume show "$name" -f value -c status 2>/dev/null || true
}

server_has_volume() {
  local server_name="$1" volume_name="$2" volume_id
  volume_id=$(openstack volume show "$volume_name" -f value -c id 2>/dev/null || true)
  [[ -n "$volume_id" ]] && openstack server volume list "$server_name" -f value -c ID 2>/dev/null | grep -Fx "$volume_id" >/dev/null 2>&1
}

wait_for_loadbalancer_active() {
  local name="$1"
  local max_sec="${2:-$LB_WAIT_SEC}"
  local sleep_sec=10
  local elapsed=0 status
  log "⏳ Waiting for load balancer '$name' to become ACTIVE (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack loadbalancer show "$name" -f value -c provisioning_status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "ACTIVE" ]]; then
      ok "Load balancer '$name' is ACTIVE (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "ERROR" ]]; then
      err "BLOCKER: Load balancer '$name' provisioning ERROR after ${elapsed}s"
      warn "  NEXT STEP: 'openstack loadbalancer show $name' for operating_status details"
      return 1
    fi
    log "  ... LB '$name' provisioning_status=$status  elapsed=${elapsed}s / ${max_sec}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Load balancer '$name' did not reach ACTIVE after ${max_sec}s"
  return 1
}

subnet_id_from_name() {
  openstack subnet show "$1" -f value -c id 2>/dev/null || true
}

instance_ip_on_network() {
  local server_name="$1" network_name="$2" ports_line ip line
  ports_line=$(openstack port list --server "$server_name" --network "$network_name" -f value -c "Fixed IP Addresses" 2>/dev/null | head -n 1 || true)
  if [[ -n "$ports_line" ]]; then
    ip=$(echo "$ports_line" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1 || true)
    [[ -n "$ip" ]] && { echo "$ip"; return 0; }
  fi
  line=$(openstack server show "$server_name" -f value -c addresses 2>/dev/null | tr "," "\n" | sed "s/^ *//g" | grep "^${network_name}=" | head -n 1 || true)
  [[ -z "$line" ]] && return 0
  ip=$(echo "$line" | sed -E 's/^[^=]+=([0-9.]+).*/\1/g')
  echo "$ip"
}

wait_for_instance_ip_on_network() {
  local server_name="$1" network_name="$2"
  local max_sec="${3:-120}" sleep_sec=5
  local elapsed=0 ip
  log "⏳ Waiting for IP on network '$network_name' for server '$server_name' ..."
  while (( elapsed < max_sec )); do
    ip=$(instance_ip_on_network "$server_name" "$network_name")
    if [[ -n "$ip" ]]; then
      log "  IP resolved: $server_name → $ip"
      echo "$ip"; return 0
    fi
    sleep "$sleep_sec"; elapsed=$((elapsed + sleep_sec))
  done
  warn "Could not resolve IP for $server_name on $network_name after ${max_sec}s"
  return 1
}

pool_has_member_ip() {
  openstack loadbalancer member list "$1" -f value -c address 2>/dev/null | grep -Fx "$2" >/dev/null 2>&1
}

loadbalancer_vip_port_id() {
  openstack loadbalancer show "$1" -f value -c vip_port_id 2>/dev/null || true
}

# NOTE: Floating IP helpers kept for reference but are NOT called by this script.
# Floating IPs are assigned MANUALLY after deployment completes.
server_has_floating_ip() {
  local out; out=$(openstack floating ip list --server "$1" -f value -c "Floating IP Address" 2>/dev/null || true)
  [[ -n "$(echo "$out" | tr -d "[:space:]")" ]]
}

port_has_floating_ip() {
  local out; out=$(openstack floating ip list --port "$1" -f value -c "Floating IP Address" 2>/dev/null || true)
  [[ -n "$(echo "$out" | tr -d "[:space:]")" ]]
}

log "Deploy script started at $(date)"
log "Floating IP assignment: SKIPPED (assign manually via Horizon or CLI after deploy)"
log "Server wait timeout   : ${SERVER_WAIT_SEC}s"
log "LB wait timeout       : ${LB_WAIT_SEC}s"
log "Collision policy      : ${RESOURCE_COLLISION_POLICY}"

phase_banner "PHASE 3: Volume Creation — pre-provision block storage (Cinder is fast, do it early)" "PHASE 4: Compute launch next"
create_or_reuse volume data-u24-postgresl-1 os volume create --size 75 --type Performance data-u24-postgresl-1
create_or_reuse volume data-windows-server-2016-sql-server-2019-1 os volume create --size 50 --type Performance data-windows-server-2016-sql-server-2019-1
create_or_reuse volume data-u24-frontend-1 os volume create --size 75 --type Performance data-u24-frontend-1
create_or_reuse volume data-u24-frontend-2 os volume create --size 75 --type Performance data-u24-frontend-2
create_or_reuse volume data-windows-server-2019re-1 os volume create --size 75 --type Performance data-windows-server-2019re-1
create_or_reuse volume data-win2019websql2019-1 os volume create --size 75 --type Performance data-win2019websql2019-1

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "✅  DEPLOY COMPLETE at $(date)"
log "   Resources created : $DEPLOY_CREATED"
log "   Resources skipped : $DEPLOY_SKIPPED (already existed)"
log "   Errors encountered: $DEPLOY_ERRORS"
if (( DEPLOY_ERRORS > 0 )); then
  warn "  Review errors above — failed resources may need manual cleanup or re-run"
fi
log ""
log "NEXT STEPS (manual)"
log "  1. Assign Floating IPs to VMs and LB VIPs via Horizon or:"
log "       openstack floating ip create PUBLICNET"
log "       openstack server add floating ip <server> <fip>"
log "  2. Verify instances: openstack server list"
log "  3. Verify LBs:       openstack loadbalancer list"
log "  4. Verify volumes:   openstack volume list"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
