#!/usr/bin/env bash
# Generated by OSPC→FLEX Deployer — do NOT edit by hand.
# Floating IP association is enabled for every VM, best effort.
set -uo pipefail

# ── Runtime config (override from environment before running) ──────────────
SERVER_WAIT_SEC="${SERVER_WAIT_SEC:-600}"       # 10 min per server active-wait
VOLUME_WAIT_SEC="${VOLUME_WAIT_SEC:-300}"       # 5 min per volume available-wait
LB_WAIT_SEC="${LB_WAIT_SEC:-480}"               # 8 min per LB active-wait
OS_CMD_TIMEOUT_SEC="${OS_CMD_TIMEOUT_SEC:-30}"  # 30s per API call — skip if exceeded
KEY_NAME="${KEY_NAME:-latopras}"                # default FLEX Linux keypair
RESOURCE_COLLISION_POLICY="${RESOURCE_COLLISION_POLICY:-reuse}"
ROLLBACK_AUTO_APPROVE=1                          # never prompt; rollback always runs
ROLLBACK_SCRIPT_PATH="${ROLLBACK_SCRIPT_PATH:-/home/dzoan/OSPC2FLEX/osflex-deployer-fullmig-5.0.0420current/uploads/last_rollback_$(date +%Y%m%d_%H%M%S).sh}"
DEPLOY_ERRORS=0
DEPLOY_SKIPPED=0
DEPLOY_CREATED=0
DEPLOY_TIMEOUTS=0
_ROLLBACK_CMDS=()   # populated at runtime; only resources CREATED (not reused) are added

# ── Timestamped logging ──────────────────────────────────────────────────────
log()  { echo "[$(date '+%H:%M:%S')] $*"; }
warn() { echo "[$(date '+%H:%M:%S')] ⚠  $*" >&2; }
err()  { echo "[$(date '+%H:%M:%S')] ✖  $*" >&2; DEPLOY_ERRORS=$((DEPLOY_ERRORS+1)); }
ok()   { echo "[$(date '+%H:%M:%S')] ✔  $*"; DEPLOY_CREATED=$((DEPLOY_CREATED+1)); }
skip() { echo "[$(date '+%H:%M:%S')] ↩  $*"; DEPLOY_SKIPPED=$((DEPLOY_SKIPPED+1)); }

phase_banner() {
  local msg="$1"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  log "🚀  $msg"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
}

# ── Guarded openstack wrapper ─────────────────────────────────────────────────
run_with_timeout() {
  local timeout_sec="$1"
  shift
  "$@" &
  local pid=$!
  local start_ts elapsed
  start_ts=$(date +%s)
  while kill -0 "$pid" 2>/dev/null; do
    elapsed=$(( $(date +%s) - start_ts ))
    if (( elapsed >= timeout_sec )); then
      warn "⏭  TIMEOUT ${timeout_sec}s — SKIPPING task and continuing deploy: $*"
      kill -TERM "$pid" 2>/dev/null || true; sleep 1
      kill -KILL "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
      DEPLOY_TIMEOUTS=$((DEPLOY_TIMEOUTS+1))
      return 0   # skip — do NOT block the rest of the deploy
    fi
    sleep 1
  done
  wait "$pid"
}

os() {
  log "+ openstack $*"
  run_with_timeout "$OS_CMD_TIMEOUT_SEC" openstack "$@"
}

# ── Resource idempotency ──────────────────────────────────────────────────────
resource_exists() {
  local kind="$1" name="$2"
  case "$kind" in
    network)       openstack network show "$name" >/dev/null 2>&1 ;;
    subnet)        openstack subnet show "$name" >/dev/null 2>&1 ;;
    router)        openstack router show "$name" >/dev/null 2>&1 ;;
    security_group) openstack security group show "$name" >/dev/null 2>&1 ;;
    instance)      openstack server show "$name" >/dev/null 2>&1 ;;
    volume)        openstack volume show "$name" >/dev/null 2>&1 ;;
    load_balancer) openstack loadbalancer show "$name" >/dev/null 2>&1 ;;
    listener)      openstack loadbalancer listener show "$name" >/dev/null 2>&1 ;;
    pool)          openstack loadbalancer pool show "$name" >/dev/null 2>&1 ;;
    *) return 1 ;;
  esac
}

create_or_reuse() {
  local kind="$1" name="$2"
  shift 2
  if resource_exists "$kind" "$name"; then
    if [[ "$RESOURCE_COLLISION_POLICY" == "fail" ]]; then
      err "BLOCKER: $kind '$name' already exists and RESOURCE_COLLISION_POLICY=fail"
      return 1
    fi
    skip "Already exists — reusing $kind: $name"
    return 0
  fi
  log "Creating $kind: $name ..."
  local _create_log; _create_log=$(mktemp)
  if "$@" 2>"$_create_log"; then
    rm -f "$_create_log"
    ok "Created $kind: $name"
    _rollback_push "$kind" "$name"
  else
    cat "$_create_log" >&2
    if [[ "$kind" == "instance" ]] && grep -qi "Invalid key_name" "$_create_log"; then
      warn "Invalid key_name rejected by Nova; retrying instance $name without --key-name."
      KEY_NAME=""
      local _retry=() _skip_next=0 _arg
      for _arg in "$@"; do
        if (( _skip_next )); then _skip_next=0; continue; fi
        if [[ "$_arg" == "--key-name" ]]; then _skip_next=1; continue; fi
        _retry+=("$_arg")
      done
      if "${_retry[@]}"; then
        rm -f "$_create_log"
        ok "Created $kind: $name without keypair"
        _rollback_push "$kind" "$name"
        return 0
      fi
    fi
    rm -f "$_create_log"
    err "FAILED to create $kind: $name — check output above for reason"
    if [[ "$kind" == "instance" ]]; then
      warn "  Common blockers for instances:"
      warn "    • Flavor disk too small for image (check 'minimum_disk' in image metadata)"
      warn "    • Quota exceeded (check 'openstack quota show')"
      warn "    • Network not reachable (check phase 1 succeeded)"
      warn "    • Key pair does not exist in project"
    fi
  fi
}

# ── Per-run rollback tracker (only NEW resources, not pre-existing ones) ─────
_rollback_push() {
  local kind="$1" name="$2" cmd
  case "$kind" in
    network)        cmd="openstack network delete \"$name\" || true" ;;
    subnet)         cmd="openstack subnet delete \"$name\" || true" ;;
    router)         cmd="openstack router remove subnet \"$name\" \"${SUBNET_NAME:-tenant-subnet}\" || true; openstack router unset --external-gateway \"$name\" || true; openstack router delete \"$name\" || true" ;;
    security_group) cmd="openstack security group delete \"$name\" || true" ;;
    instance)       cmd="openstack server delete --wait \"$name\" 2>/dev/null || openstack server delete \"$name\" || true" ;;
    volume)         cmd="openstack volume delete --force \"$name\" || true" ;;
    load_balancer)  cmd="openstack loadbalancer delete --cascade \"$name\" 2>/dev/null || openstack loadbalancer delete \"$name\" || true" ;;
    listener|pool)  return 0 ;;
    *)              return 0 ;;
  esac
  _ROLLBACK_CMDS=("$cmd" "${_ROLLBACK_CMDS[@]+${_ROLLBACK_CMDS[@]}}")
}

_finalize_rollback() {
  [[ ${#_ROLLBACK_CMDS[@]} -eq 0 ]] && { warn "No new resources created — rollback script skipped."; return 0; }
  local n=${#_ROLLBACK_CMDS[@]} i
  {
    echo '#!/usr/bin/env bash'
    echo '# AUTO-GENERATED rollback — deletes ONLY resources created in THIS run.'
    echo '# Pre-existing (reused) resources are NOT touched.'
    echo 'set -uo pipefail'
    echo 'ROLLBACK_AUTO_APPROVE=1'
    echo 'log() { echo "[$(date +%H:%M:%S)] $*"; }'
    printf "log \"Starting rollback: $n step(s) in reverse creation order\"\n"
    for (( i=0; i<n; i++ )); do
      printf "log \"  [%d/%d] %s\"\n" "$((i+1))" "$n" "${_ROLLBACK_CMDS[$i]}"
      printf "%s\n" "${_ROLLBACK_CMDS[$i]}"
    done
    echo 'log "✅  Rollback complete."'
  } > "$ROLLBACK_SCRIPT_PATH"
  chmod +x "$ROLLBACK_SCRIPT_PATH"
  log "↩  Rollback script written: $ROLLBACK_SCRIPT_PATH ($n steps)"
}

# ── Wait helpers (with live progress output) ──────────────────────────────────
wait_for_server_active() {
  local name="$1"
  local max_sec="${2:-$SERVER_WAIT_SEC}"
  local sleep_sec=10
  local elapsed=0 status fault
  log "⏳ Waiting for server '$name' to become ACTIVE (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack server show "$name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "ACTIVE" ]]; then
      ok "Server '$name' is ACTIVE (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "ERROR" ]]; then
      fault=$(openstack server show "$name" -f value -c fault 2>/dev/null || echo "unknown fault")
      err "BLOCKER: Server '$name' entered ERROR state after ${elapsed}s"
      err "  Fault details: $fault"
      warn "  Common causes:"
      warn "    • Flavor disk smaller than image minimum_disk — use --boot-from-volume"
      warn "    • Host capacity insufficient — try a different availability zone"
      warn "    • Image not found or inaccessible in this region"
      warn "  NEXT STEP: Delete the error server and re-create with a larger flavor or boot-from-volume"
      return 1
    fi
    log "  ... server '$name' status=$status  elapsed=${elapsed}s / ${max_sec}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Server '$name' did not reach ACTIVE after ${max_sec}s (last status: $status)"
  warn "  NEXT STEP: Check 'openstack server show $name' — if still BUILD, try waiting longer"
  warn "            If ERROR, see fault reason above and re-create with corrected params"
  return 1
}

wait_for_volume_available() {
  local name="$1"
  local max_sec="${2:-$VOLUME_WAIT_SEC}"
  local sleep_sec=5
  local elapsed=0 status
  log "⏳ Waiting for volume '$name' to become available (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack volume show "$name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "available" ]]; then
      ok "Volume '$name' is available (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "error" ]]; then
      err "BLOCKER: Volume '$name' entered error state after ${elapsed}s"
      warn "  NEXT STEP: Delete the volume and re-create, or check Cinder quota"
      return 1
    fi
    log "  ... volume '$name' status=$status  elapsed=${elapsed}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Volume '$name' not available after ${max_sec}s"
  return 1
}

volume_status() {
  local name="$1"
  openstack volume show "$name" -f value -c status 2>/dev/null || true
}

server_has_volume() {
  local server_name="$1" volume_name="$2" volume_id
  volume_id=$(openstack volume show "$volume_name" -f value -c id 2>/dev/null || true)
  [[ -n "$volume_id" ]] && openstack server volume list "$server_name" -f value -c ID 2>/dev/null | grep -Fx "$volume_id" >/dev/null 2>&1
}

# -- Volume-attach with fast retry/skip (no 600s block) --
# Usage: _vol_attach_with_retry <server_name> <volume_name> [max_trials]
# Skips gracefully after max_trials instead of blocking forever.
_vol_attach_with_retry() {
  local inst_name="$1" vol_name="$2"
  local max_trials="${3:-${MAX_VOL_ATTACH_TRIALS:-3}}"
  local attempt=0 srv_status vol_status
  while (( attempt < max_trials )); do
    attempt=$(( attempt + 1 ))
    srv_status=$(openstack server show "$inst_name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$srv_status" != "ACTIVE" ]]; then
      warn "  [Vol Attach] $inst_name is $srv_status -- trial $attempt/$max_trials"
      if (( attempt >= max_trials )); then
        warn "  [Vol Attach] SKIP: $inst_name never became ACTIVE after $max_trials trials -- attach $vol_name manually"
        (( DEPLOY_ERRORS++ )) || true; return 1
      fi
      sleep 15; continue
    fi
    if server_has_volume "$inst_name" "$vol_name"; then
      ok "Volume $vol_name already attached to $inst_name; skipping."; return 0
    fi
    vol_status=$(openstack volume show "$vol_name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$vol_status" == "in-use" ]]; then
      warn "  [Vol Attach] Volume $vol_name is in-use (not attached to $inst_name); skipping."; return 1
    fi
    if [[ "$vol_status" != "available" ]]; then
      warn "  [Vol Attach] Volume $vol_name is $vol_status -- trial $attempt/$max_trials"
      if (( attempt >= max_trials )); then
        warn "  [Vol Attach] SKIP: volume $vol_name not available after $max_trials trials -- attach manually"
        (( DEPLOY_ERRORS++ )) || true; return 1
      fi
      sleep 15; continue
    fi
    if openstack server add volume "$inst_name" "$vol_name" 2>/dev/null; then
      ok "✅ Volume '$vol_name' attached to '$inst_name' (trial $attempt)"; return 0
    fi
    warn "  [Vol Attach] Attach command failed — trial $attempt/$max_trials (retrying in 10s)"
    sleep 10
  done
  warn "  [Vol Attach] ⏭ SKIP: '$vol_name' → '$inst_name' after $max_trials failed trials — attach manually"
  (( DEPLOY_ERRORS++ )) || true; return 1
}

wait_for_loadbalancer_active() {
  local name="$1"
  local max_sec="${2:-$LB_WAIT_SEC}"
  local sleep_sec=10
  local elapsed=0 status
  log "⏳ Waiting for load balancer '$name' to become ACTIVE (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack loadbalancer show "$name" -f value -c provisioning_status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "ACTIVE" ]]; then
      ok "Load balancer '$name' is ACTIVE (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "ERROR" ]]; then
      err "BLOCKER: Load balancer '$name' provisioning ERROR after ${elapsed}s"
      warn "  NEXT STEP: 'openstack loadbalancer show $name' for operating_status details"
      return 1
    fi
    log "  ... LB '$name' provisioning_status=$status  elapsed=${elapsed}s / ${max_sec}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Load balancer '$name' did not reach ACTIVE after ${max_sec}s"
  return 1
}

subnet_id_from_name() {
  openstack subnet show "$1" -f value -c id 2>/dev/null || true
}

instance_ip_on_network() {
  local server_name="$1" network_name="$2" ports_line ip line
  ports_line=$(openstack port list --server "$server_name" --network "$network_name" -f value -c "Fixed IP Addresses" 2>/dev/null | head -n 1 || true)
  if [[ -n "$ports_line" ]]; then
    ip=$(echo "$ports_line" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1 || true)
    [[ -n "$ip" ]] && { echo "$ip"; return 0; }
  fi
  line=$(openstack server show "$server_name" -f value -c addresses 2>/dev/null | tr "," "\n" | sed "s/^ *//g" | grep "^${network_name}=" | head -n 1 || true)
  [[ -z "$line" ]] && return 0
  ip=$(echo "$line" | sed -E 's/^[^=]+=([0-9.]+).*/\1/g')
  echo "$ip"
}

wait_for_instance_ip_on_network() {
  local server_name="$1" network_name="$2"
  local max_sec="${3:-120}" sleep_sec=5
  local elapsed=0 ip
  log "⏳ Waiting for IP on network '$network_name' for server '$server_name' ..."
  while (( elapsed < max_sec )); do
    ip=$(instance_ip_on_network "$server_name" "$network_name")
    if [[ -n "$ip" ]]; then
      log "  IP resolved: $server_name → $ip"
      echo "$ip"; return 0
    fi
    sleep "$sleep_sec"; elapsed=$((elapsed + sleep_sec))
  done
  warn "Could not resolve IP for $server_name on $network_name after ${max_sec}s"
  return 1
}

pool_has_member_ip() {
  openstack loadbalancer member list "$1" -f value -c address 2>/dev/null | grep -Fx "$2" >/dev/null 2>&1
}

loadbalancer_vip_port_id() {
  openstack loadbalancer show "$1" -f value -c vip_port_id 2>/dev/null || true
}

# ── Floating IP helpers: every VM gets best-effort assignment ────────────────
server_has_floating_ip() {
  local out; out=$(openstack floating ip list --server "$1" -f value -c "Floating IP Address" 2>/dev/null || true)
  [[ -n "$(echo "$out" | tr -d "[:space:]")" ]]
}

port_has_floating_ip() {
  local out; out=$(openstack floating ip list --port "$1" -f value -c "Floating IP Address" 2>/dev/null || true)
  [[ -n "$(echo "$out" | tr -d "[:space:]")" ]]
}

assign_floating_ip() {
  local server_name="$1" public_network="$2" attempt fip
  for attempt in 1 2 3; do
    log "Floating IP attempt $attempt/3: server=$server_name network=$public_network"
    fip=$(openstack floating ip list --network "$public_network" --status DOWN -f value -c "Floating IP Address" 2>/dev/null | head -n 1 || true)
    if [[ -z "$fip" ]]; then
      fip=$(openstack floating ip create "$public_network" -f value -c floating_ip_address 2>/dev/null || true)
    fi
    if [[ -n "$fip" ]] && openstack server add floating ip "$server_name" "$fip"; then
      ok "Floating IP $fip attached to $server_name"; return 0
    fi
    warn "Floating IP attach failed for $server_name on attempt $attempt/3; retrying..."
    sleep 5
  done
  warn "Floating IP SKIP: $server_name after 3 failed attempts; continuing to next VM."
  return 0
}

log "Deploy script started at $(date)"
log "Floating IP assignment: enabled for every VM (best effort, 3 attempts)"
log "Server wait timeout   : ${SERVER_WAIT_SEC}s"
log "LB wait timeout       : ${LB_WAIT_SEC}s"
log "Collision policy      : ${RESOURCE_COLLISION_POLICY}"
if [ -n "$KEY_NAME" ]; then
  if openstack keypair show "$KEY_NAME" >/dev/null 2>&1; then
    log "Linux keypair        : $KEY_NAME"
  else
    warn "Keypair $KEY_NAME not found in target project; continuing without --key-name."
    KEY_NAME=""
  fi
fi

phase_banner "PHASE 1: Networking Foundation — networks, subnets, routers, security groups" "PHASE 2: LB Scaffold will start next"
create_or_reuse network tenant-net os network create tenant-net
create_or_reuse network PUBLICNET os network create PUBLICNET
create_or_reuse subnet tenant-subnet os subnet create --network tenant-net --subnet-range 10.60.0.0/24 tenant-subnet
create_or_reuse router tenant-router os router create tenant-router
os router set --external-gateway PUBLICNET tenant-router
os router add subnet tenant-router tenant-subnet || true
create_or_reuse security_group default os security group create default
phase_banner "PHASE 2: LB Scaffold — LB + Listener + Pool (Octavia Amphora provisioning in parallel with VM boot)" "PHASE 3: Volume Creation next"
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -z "$lb_subnet_id" ]]; then
  echo "Skipping load balancer frontend- Load-Balancer-01: subnet tenant-subnet not found." >&2
else
  create_or_reuse load_balancer 'frontend- Load-Balancer-01' os loadbalancer create --name 'frontend- Load-Balancer-01' --provider amphora --vip-subnet-id "$lb_subnet_id"
  wait_for_loadbalancer_active 'frontend- Load-Balancer-01'
  create_or_reuse listener 'frontend- Load-Balancer-01-listener' os loadbalancer listener create --name 'frontend- Load-Balancer-01-listener' --protocol HTTP --protocol-port 80 'frontend- Load-Balancer-01'
  wait_for_loadbalancer_active 'frontend- Load-Balancer-01'
  create_or_reuse pool 'frontend- Load-Balancer-01-pool' os loadbalancer pool create --name 'frontend- Load-Balancer-01-pool' --lb-algorithm WEIGHTED_LEAST_CONNECTIONS --listener 'frontend- Load-Balancer-01-listener' --protocol HTTP
  wait_for_loadbalancer_active 'frontend- Load-Balancer-01'
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -z "$lb_subnet_id" ]]; then
  echo "Skipping load balancer u24backend: subnet tenant-subnet not found." >&2
else
  create_or_reuse load_balancer u24backend os loadbalancer create --name u24backend --provider amphora --vip-subnet-id "$lb_subnet_id"
  wait_for_loadbalancer_active u24backend
  create_or_reuse listener u24backend-listener os loadbalancer listener create --name u24backend-listener --protocol HTTP --protocol-port 80 u24backend
  wait_for_loadbalancer_active u24backend
  create_or_reuse pool u24backend-pool os loadbalancer pool create --name u24backend-pool --lb-algorithm LEAST_CONNECTIONS --listener u24backend-listener --protocol HTTP
  wait_for_loadbalancer_active u24backend
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -z "$lb_subnet_id" ]]; then
  echo "Skipping load balancer DB_loadbalancer MYSQL: subnet tenant-subnet not found." >&2
else
  create_or_reuse load_balancer 'DB_loadbalancer MYSQL' os loadbalancer create --name 'DB_loadbalancer MYSQL' --provider amphora --vip-subnet-id "$lb_subnet_id"
  wait_for_loadbalancer_active 'DB_loadbalancer MYSQL'
  create_or_reuse listener 'DB_loadbalancer MYSQL-listener' os loadbalancer listener create --name 'DB_loadbalancer MYSQL-listener' --protocol MYSQL --protocol-port 3306 'DB_loadbalancer MYSQL'
  wait_for_loadbalancer_active 'DB_loadbalancer MYSQL'
  create_or_reuse pool 'DB_loadbalancer MYSQL-pool' os loadbalancer pool create --name 'DB_loadbalancer MYSQL-pool' --lb-algorithm ROUND_ROBIN --listener 'DB_loadbalancer MYSQL-listener' --protocol MYSQL
  wait_for_loadbalancer_active 'DB_loadbalancer MYSQL'
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -z "$lb_subnet_id" ]]; then
  echo "Skipping load balancer LBmariaDB: subnet tenant-subnet not found." >&2
else
  create_or_reuse load_balancer LBmariaDB os loadbalancer create --name LBmariaDB --provider amphora --vip-subnet-id "$lb_subnet_id"
  wait_for_loadbalancer_active LBmariaDB
  create_or_reuse listener LBmariaDB-listener os loadbalancer listener create --name LBmariaDB-listener --protocol MYSQL --protocol-port 3306 LBmariaDB
  wait_for_loadbalancer_active LBmariaDB
  create_or_reuse pool LBmariaDB-pool os loadbalancer pool create --name LBmariaDB-pool --lb-algorithm LEAST_CONNECTIONS --listener LBmariaDB-listener --protocol MYSQL
  wait_for_loadbalancer_active LBmariaDB
fi
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -z "$lb_subnet_id" ]]; then
  echo "Skipping load balancer perconaLB: subnet tenant-subnet not found." >&2
else
  create_or_reuse load_balancer perconaLB os loadbalancer create --name perconaLB --provider amphora --vip-subnet-id "$lb_subnet_id"
  wait_for_loadbalancer_active perconaLB
  create_or_reuse listener perconaLB-listener os loadbalancer listener create --name perconaLB-listener --protocol MYSQL --protocol-port 3306 perconaLB
  wait_for_loadbalancer_active perconaLB
  create_or_reuse pool perconaLB-pool os loadbalancer pool create --name perconaLB-pool --lb-algorithm LEAST_CONNECTIONS --listener perconaLB-listener --protocol MYSQL
  wait_for_loadbalancer_active perconaLB
fi
phase_banner "PHASE 3: Volume Creation — pre-provision block storage (Cinder is fast, do it early)" "PHASE 4: Compute launch next"
create_or_reuse volume boot-ospcwin2019 os volume create --size 80 --type Performance boot-ospcwin2019
create_or_reuse volume boot-dbian12 os volume create --size 50 --type Performance boot-dbian12
create_or_reuse volume boot-centos7 os volume create --size 80 --type Performance boot-centos7
create_or_reuse volume boot-win2019 os volume create --size 80 --type Performance boot-win2019
create_or_reuse volume boot-alma8 os volume create --size 50 --type Performance boot-alma8
create_or_reuse volume u24-green-server-data-1 os volume create --size 75 --type Performance u24-green-server-data-1
create_or_reuse volume u24-green-server-data-2 os volume create --size 75 --type Performance u24-green-server-data-2
create_or_reuse volume postgresqlu24-data-1 os volume create --size 75 --type Performance postgresqlu24-data-1
create_or_reuse volume bigjumpwindowsiad-data-1 os volume create --size 500 --type Performance bigjumpwindowsiad-data-1
create_or_reuse volume bigjim-iad-data-1 os volume create --size 80 --type Performance bigjim-iad-data-1
create_or_reuse volume bigjim-iad-data-2 os volume create --size 80 --type Performance bigjim-iad-data-2
create_or_reuse volume bigjim-iad-data-3 os volume create --size 80 --type Performance bigjim-iad-data-3
create_or_reuse volume bigjim-iad-data-4 os volume create --size 80 --type Performance bigjim-iad-data-4
create_or_reuse volume bigjim-iad-data-5 os volume create --size 80 --type Performance bigjim-iad-data-5
create_or_reuse volume bigjim-iad-data-6 os volume create --size 75 --type Performance bigjim-iad-data-6
create_or_reuse volume bigjim-iad-data-7 os volume create --size 75 --type Performance bigjim-iad-data-7
create_or_reuse volume bigjim-iad-data-8 os volume create --size 75 --type Performance bigjim-iad-data-8
create_or_reuse volume bigjim-iad-data-9 os volume create --size 75 --type Performance bigjim-iad-data-9
create_or_reuse volume bigjim-iad-data-10 os volume create --size 75 --type Performance bigjim-iad-data-10
create_or_reuse volume bigjim-iad-data-11 os volume create --size 75 --type Performance bigjim-iad-data-11
create_or_reuse volume bigjim-iad-data-12 os volume create --size 80 --type Performance bigjim-iad-data-12
create_or_reuse volume bigjim-iad-data-13 os volume create --size 75 --type Performance bigjim-iad-data-13
create_or_reuse volume bigjim-iad-data-14 os volume create --size 75 --type Performance bigjim-iad-data-14
create_or_reuse volume bigjim-iad-data-15 os volume create --size 75 --type Performance bigjim-iad-data-15
create_or_reuse volume bigjim-iad-data-16 os volume create --size 75 --type Performance bigjim-iad-data-16
create_or_reuse volume bigjim-iad-data-17 os volume create --size 80 --type Performance bigjim-iad-data-17
create_or_reuse volume bigjim-iad-data-18 os volume create --size 80 --type Performance bigjim-iad-data-18
create_or_reuse volume bigjim-iad-data-19 os volume create --size 80 --type Performance bigjim-iad-data-19
create_or_reuse volume bigjim-iad-data-20 os volume create --size 80 --type Performance bigjim-iad-data-20
create_or_reuse volume bigjim-iad-data-21 os volume create --size 80 --type Performance bigjim-iad-data-21
create_or_reuse volume bigjim-iad-data-22 os volume create --size 80 --type Performance bigjim-iad-data-22
create_or_reuse volume bigjim-iad-data-23 os volume create --size 80 --type Performance bigjim-iad-data-23
create_or_reuse volume bigjim-iad-data-24 os volume create --size 80 --type Performance bigjim-iad-data-24
create_or_reuse volume bigjim-iad-data-25 os volume create --size 80 --type Performance bigjim-iad-data-25
create_or_reuse volume bigjim-iad-data-26 os volume create --size 80 --type Performance bigjim-iad-data-26
create_or_reuse volume bigjim-iad-data-27 os volume create --size 80 --type Performance bigjim-iad-data-27
create_or_reuse volume bigjim-iad-data-28 os volume create --size 80 --type Performance bigjim-iad-data-28
create_or_reuse volume bigjim-iad-data-29 os volume create --size 75 --type Performance bigjim-iad-data-29
create_or_reuse volume bigjim-iad-data-30 os volume create --size 75 --type Performance bigjim-iad-data-30
create_or_reuse volume bigjim-iad-data-31 os volume create --size 75 --type Performance bigjim-iad-data-31
create_or_reuse volume bigjim-iad-data-32 os volume create --size 75 --type Performance bigjim-iad-data-32
create_or_reuse volume bigjim-iad-data-33 os volume create --size 75 --type Performance bigjim-iad-data-33
create_or_reuse volume bigjim-iad-data-34 os volume create --size 75 --type Performance bigjim-iad-data-34
create_or_reuse volume bigjim-iad-data-35 os volume create --size 75 --type Performance bigjim-iad-data-35
create_or_reuse volume bigjim-iad-data-36 os volume create --size 75 --type Performance bigjim-iad-data-36
create_or_reuse volume bigjim-iad-data-37 os volume create --size 75 --type Performance bigjim-iad-data-37
create_or_reuse volume bigjim-iad-data-38 os volume create --size 75 --type Performance bigjim-iad-data-38
create_or_reuse volume bigjim-iad-data-39 os volume create --size 75 --type Performance bigjim-iad-data-39
create_or_reuse volume bigjim-iad-data-40 os volume create --size 75 --type Performance bigjim-iad-data-40
create_or_reuse volume bigjim-iad-data-41 os volume create --size 75 --type Performance bigjim-iad-data-41
create_or_reuse volume bigjim-iad-data-42 os volume create --size 75 --type Performance bigjim-iad-data-42
create_or_reuse volume bigjim-iad-data-43 os volume create --size 75 --type Performance bigjim-iad-data-43
create_or_reuse volume bigjim-iad-data-44 os volume create --size 75 --type Performance bigjim-iad-data-44
create_or_reuse volume bigjim-iad-data-45 os volume create --size 75 --type Performance bigjim-iad-data-45
create_or_reuse volume bigjim-iad-data-46 os volume create --size 75 --type Performance bigjim-iad-data-46
create_or_reuse volume bigjim-iad-data-47 os volume create --size 75 --type Performance bigjim-iad-data-47
create_or_reuse volume bigjim-iad-data-48 os volume create --size 75 --type Performance bigjim-iad-data-48
create_or_reuse volume bigjim-iad-data-49 os volume create --size 75 --type Performance bigjim-iad-data-49
create_or_reuse volume bigjim-iad-data-50 os volume create --size 75 --type Performance bigjim-iad-data-50
create_or_reuse volume bigjim-iad-data-51 os volume create --size 75 --type Performance bigjim-iad-data-51
create_or_reuse volume bigjim-iad-data-52 os volume create --size 500 --type Performance bigjim-iad-data-52
create_or_reuse volume u20-data-1 os volume create --size 75 --type Performance u20-data-1
create_or_reuse volume alma9-data-1 os volume create --size 1024 --type Performance alma9-data-1
phase_banner "PHASE 4: Compute & DB Creation — Windows VMs fired in background first (sysprep is slow), Linux VMs and DB servers inline" "PHASE 5: LB Creation next"
echo "  -> Firing Windows VMs in background (sysprep takes longest)..."
_WIN_PIDS=()
( # Windows VM: ospcwin2019
echo "Skipping instance ospcwin2019: flavor, image, and network required."
) &
_WIN_PIDS+=($!)
( # Windows VM: opscwin2016
create_or_reuse instance opscwin2016 os server create --flavor gp.0.2.4 --image 'Windows Server 2016' --network tenant-net --security-group default --password DLIarOpvSBa24D opscwin2016
) &
_WIN_PIDS+=($!)
( # Windows VM: win2019
echo "Skipping instance win2019: flavor, image, and network required."
) &
_WIN_PIDS+=($!)
( # Windows VM: windows2016
create_or_reuse instance windows2016 os server create --flavor gp.0.2.4 --image 'Windows Server 2016' --network tenant-net --security-group default --password ehbyFEYsyATwq5 windows2016
) &
_WIN_PIDS+=($!)
echo "  -> Provisioning Linux VMs..."
create_or_reuse instance Server-27 os server create --flavor gp.0.2.2 --image 'AlmaLinux 9' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} Server-27
create_or_reuse instance haproxyopsc os server create --flavor gp.0.4.4 --image 'Ubuntu 24.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} haproxyopsc
create_or_reuse instance u24clean os server create --flavor gp.0.2.2 --image 'Ubuntu 24.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} u24clean
create_or_reuse instance debian12 os server create --flavor gp.0.2.2 --image 'Debian 12' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} debian12
create_or_reuse instance 'u24 green server' os server create --flavor gp.0.2.2 --image 'Ubuntu 24.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} 'u24 green server'
create_or_reuse instance u-22 os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} u-22
create_or_reuse instance Server-21 os server create --flavor gp.0.2.2 --image 'AlmaLinux 9' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} Server-21
create_or_reuse instance musicradio os server create --flavor gp.0.2.2 --image 'Ubuntu 24.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} musicradio
create_or_reuse instance postgresqlU24 os server create --flavor gp.0.2.2 --image 'Ubuntu 24.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} postgresqlU24
create_or_reuse instance 'mongo db u24' os server create --flavor gp.0.2.2 --image 'Ubuntu 24.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} 'mongo db u24'
create_or_reuse instance bigjumpwindowsiad os server create --flavor gp.0.16.64 --image 'Ubuntu 24.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} bigjumpwindowsiad
create_or_reuse instance Bigjim-iad os server create --flavor gp.0.16.64 --image 'Ubuntu 24.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} Bigjim-iad
create_or_reuse instance jenkins os server create --flavor gp.0.4.4 --image 'Rocky Linux 8' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} jenkins
echo "Skipping instance centos7: flavor, image, and network required."
create_or_reuse instance debian11new os server create --flavor gp.0.2.2 --image 'Debian 11' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} debian11new
create_or_reuse instance dbian10new os server create --flavor gp.0.2.2 --image 'Debian 11' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} dbian10new
create_or_reuse instance u20 os server create --flavor gp.0.2.2 --image 'Ubuntu 20.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} u20
create_or_reuse instance rocky9 os server create --flavor gp.0.2.2 --image 'Rocky Linux 9' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} rocky9
echo "Skipping instance alma8: flavor, image, and network required."
create_or_reuse instance dbian12 os server create --flavor gp.0.2.4 --image 'Debian 12' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} dbian12
create_or_reuse instance Alma9 os server create --flavor gp.0.4.8 --image 'AlmaLinux 9' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} Alma9
create_or_reuse instance rocky8 os server create --flavor gp.0.4.8 --image 'Rocky Linux 8' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} rocky8
create_or_reuse instance 'HA percona 8-02' os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} 'HA percona 8-02'
create_or_reuse instance drupal os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} drupal
create_or_reuse instance dbaasmariadb os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} dbaasmariadb
create_or_reuse instance HA-Mysql8-01 os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} HA-Mysql8-01
create_or_reuse instance HA-mariaDB-02 os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} HA-mariaDB-02
create_or_reuse instance drupalphp_Database os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} drupalphp_Database
create_or_reuse instance 'HA percona 8-03' os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} 'HA percona 8-03'
create_or_reuse instance HA-mariaDB-03 os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} HA-mariaDB-03
create_or_reuse instance lamp_Database os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} lamp_Database
create_or_reuse instance HAdbaasSql-03 os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} HAdbaasSql-03
create_or_reuse instance Stack-05_Database os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} Stack-05_Database
create_or_reuse instance HAmysql-01 os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} HAmysql-01
create_or_reuse instance mariad1 os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} mariad1
create_or_reuse instance hadbaas-vip-03 os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} hadbaas-vip-03
create_or_reuse instance Instance-21 os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} Instance-21
create_or_reuse instance mysql8instance os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} mysql8instance
create_or_reuse instance sql os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} sql
create_or_reuse instance Mariadb os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} Mariadb
create_or_reuse instance hadbaas-vip-01 os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} hadbaas-vip-01
create_or_reuse instance Instance-20 os server create --flavor gp.0.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default ${KEY_NAME:+--key-name "$KEY_NAME"} Instance-20
echo "  -> Waiting for Windows VMs to finish provisioning..."
for _wpid in "${_WIN_PIDS[@]}"; do wait "$_wpid" || true; done
echo "  -> All Windows VMs provisioning complete."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "PHASE 4B: Floating IP Assignment — best effort, 3 trials per VM"
wait_for_server_active ospcwin2019 || true
if server_has_floating_ip ospcwin2019; then
  log "Floating IP already assigned to ospcwin2019; skipping."
else
  assign_floating_ip ospcwin2019 PUBLICNET
fi
wait_for_server_active opscwin2016 || true
if server_has_floating_ip opscwin2016; then
  log "Floating IP already assigned to opscwin2016; skipping."
else
  assign_floating_ip opscwin2016 PUBLICNET
fi
wait_for_server_active win2019 || true
if server_has_floating_ip win2019; then
  log "Floating IP already assigned to win2019; skipping."
else
  assign_floating_ip win2019 PUBLICNET
fi
wait_for_server_active windows2016 || true
if server_has_floating_ip windows2016; then
  log "Floating IP already assigned to windows2016; skipping."
else
  assign_floating_ip windows2016 PUBLICNET
fi
wait_for_server_active Server-27 || true
if server_has_floating_ip Server-27; then
  log "Floating IP already assigned to Server-27; skipping."
else
  assign_floating_ip Server-27 PUBLICNET
fi
wait_for_server_active haproxyopsc || true
if server_has_floating_ip haproxyopsc; then
  log "Floating IP already assigned to haproxyopsc; skipping."
else
  assign_floating_ip haproxyopsc PUBLICNET
fi
wait_for_server_active u24clean || true
if server_has_floating_ip u24clean; then
  log "Floating IP already assigned to u24clean; skipping."
else
  assign_floating_ip u24clean PUBLICNET
fi
wait_for_server_active debian12 || true
if server_has_floating_ip debian12; then
  log "Floating IP already assigned to debian12; skipping."
else
  assign_floating_ip debian12 PUBLICNET
fi
wait_for_server_active 'u24 green server' || true
if server_has_floating_ip 'u24 green server'; then
  log "Floating IP already assigned to u24 green server; skipping."
else
  assign_floating_ip 'u24 green server' PUBLICNET
fi
wait_for_server_active u-22 || true
if server_has_floating_ip u-22; then
  log "Floating IP already assigned to u-22; skipping."
else
  assign_floating_ip u-22 PUBLICNET
fi
wait_for_server_active Server-21 || true
if server_has_floating_ip Server-21; then
  log "Floating IP already assigned to Server-21; skipping."
else
  assign_floating_ip Server-21 PUBLICNET
fi
wait_for_server_active musicradio || true
if server_has_floating_ip musicradio; then
  log "Floating IP already assigned to musicradio; skipping."
else
  assign_floating_ip musicradio PUBLICNET
fi
wait_for_server_active postgresqlU24 || true
if server_has_floating_ip postgresqlU24; then
  log "Floating IP already assigned to postgresqlU24; skipping."
else
  assign_floating_ip postgresqlU24 PUBLICNET
fi
wait_for_server_active 'mongo db u24' || true
if server_has_floating_ip 'mongo db u24'; then
  log "Floating IP already assigned to mongo db u24; skipping."
else
  assign_floating_ip 'mongo db u24' PUBLICNET
fi
wait_for_server_active bigjumpwindowsiad || true
if server_has_floating_ip bigjumpwindowsiad; then
  log "Floating IP already assigned to bigjumpwindowsiad; skipping."
else
  assign_floating_ip bigjumpwindowsiad PUBLICNET
fi
wait_for_server_active Bigjim-iad || true
if server_has_floating_ip Bigjim-iad; then
  log "Floating IP already assigned to Bigjim-iad; skipping."
else
  assign_floating_ip Bigjim-iad PUBLICNET
fi
wait_for_server_active jenkins || true
if server_has_floating_ip jenkins; then
  log "Floating IP already assigned to jenkins; skipping."
else
  assign_floating_ip jenkins PUBLICNET
fi
wait_for_server_active centos7 || true
if server_has_floating_ip centos7; then
  log "Floating IP already assigned to centos7; skipping."
else
  assign_floating_ip centos7 PUBLICNET
fi
wait_for_server_active debian11new || true
if server_has_floating_ip debian11new; then
  log "Floating IP already assigned to debian11new; skipping."
else
  assign_floating_ip debian11new PUBLICNET
fi
wait_for_server_active dbian10new || true
if server_has_floating_ip dbian10new; then
  log "Floating IP already assigned to dbian10new; skipping."
else
  assign_floating_ip dbian10new PUBLICNET
fi
wait_for_server_active u20 || true
if server_has_floating_ip u20; then
  log "Floating IP already assigned to u20; skipping."
else
  assign_floating_ip u20 PUBLICNET
fi
wait_for_server_active rocky9 || true
if server_has_floating_ip rocky9; then
  log "Floating IP already assigned to rocky9; skipping."
else
  assign_floating_ip rocky9 PUBLICNET
fi
wait_for_server_active alma8 || true
if server_has_floating_ip alma8; then
  log "Floating IP already assigned to alma8; skipping."
else
  assign_floating_ip alma8 PUBLICNET
fi
wait_for_server_active dbian12 || true
if server_has_floating_ip dbian12; then
  log "Floating IP already assigned to dbian12; skipping."
else
  assign_floating_ip dbian12 PUBLICNET
fi
wait_for_server_active Alma9 || true
if server_has_floating_ip Alma9; then
  log "Floating IP already assigned to Alma9; skipping."
else
  assign_floating_ip Alma9 PUBLICNET
fi
wait_for_server_active rocky8 || true
if server_has_floating_ip rocky8; then
  log "Floating IP already assigned to rocky8; skipping."
else
  assign_floating_ip rocky8 PUBLICNET
fi
wait_for_server_active 'HA percona 8-02' || true
if server_has_floating_ip 'HA percona 8-02'; then
  log "Floating IP already assigned to HA percona 8-02; skipping."
else
  assign_floating_ip 'HA percona 8-02' PUBLICNET
fi
wait_for_server_active drupal || true
if server_has_floating_ip drupal; then
  log "Floating IP already assigned to drupal; skipping."
else
  assign_floating_ip drupal PUBLICNET
fi
wait_for_server_active dbaasmariadb || true
if server_has_floating_ip dbaasmariadb; then
  log "Floating IP already assigned to dbaasmariadb; skipping."
else
  assign_floating_ip dbaasmariadb PUBLICNET
fi
wait_for_server_active HA-Mysql8-01 || true
if server_has_floating_ip HA-Mysql8-01; then
  log "Floating IP already assigned to HA-Mysql8-01; skipping."
else
  assign_floating_ip HA-Mysql8-01 PUBLICNET
fi
wait_for_server_active HA-mariaDB-02 || true
if server_has_floating_ip HA-mariaDB-02; then
  log "Floating IP already assigned to HA-mariaDB-02; skipping."
else
  assign_floating_ip HA-mariaDB-02 PUBLICNET
fi
wait_for_server_active drupalphp_Database || true
if server_has_floating_ip drupalphp_Database; then
  log "Floating IP already assigned to drupalphp_Database; skipping."
else
  assign_floating_ip drupalphp_Database PUBLICNET
fi
wait_for_server_active 'HA percona 8-03' || true
if server_has_floating_ip 'HA percona 8-03'; then
  log "Floating IP already assigned to HA percona 8-03; skipping."
else
  assign_floating_ip 'HA percona 8-03' PUBLICNET
fi
wait_for_server_active HA-mariaDB-03 || true
if server_has_floating_ip HA-mariaDB-03; then
  log "Floating IP already assigned to HA-mariaDB-03; skipping."
else
  assign_floating_ip HA-mariaDB-03 PUBLICNET
fi
wait_for_server_active lamp_Database || true
if server_has_floating_ip lamp_Database; then
  log "Floating IP already assigned to lamp_Database; skipping."
else
  assign_floating_ip lamp_Database PUBLICNET
fi
wait_for_server_active HAdbaasSql-03 || true
if server_has_floating_ip HAdbaasSql-03; then
  log "Floating IP already assigned to HAdbaasSql-03; skipping."
else
  assign_floating_ip HAdbaasSql-03 PUBLICNET
fi
wait_for_server_active Stack-05_Database || true
if server_has_floating_ip Stack-05_Database; then
  log "Floating IP already assigned to Stack-05_Database; skipping."
else
  assign_floating_ip Stack-05_Database PUBLICNET
fi
wait_for_server_active HAmysql-01 || true
if server_has_floating_ip HAmysql-01; then
  log "Floating IP already assigned to HAmysql-01; skipping."
else
  assign_floating_ip HAmysql-01 PUBLICNET
fi
wait_for_server_active mariad1 || true
if server_has_floating_ip mariad1; then
  log "Floating IP already assigned to mariad1; skipping."
else
  assign_floating_ip mariad1 PUBLICNET
fi
wait_for_server_active hadbaas-vip-03 || true
if server_has_floating_ip hadbaas-vip-03; then
  log "Floating IP already assigned to hadbaas-vip-03; skipping."
else
  assign_floating_ip hadbaas-vip-03 PUBLICNET
fi
wait_for_server_active Instance-21 || true
if server_has_floating_ip Instance-21; then
  log "Floating IP already assigned to Instance-21; skipping."
else
  assign_floating_ip Instance-21 PUBLICNET
fi
wait_for_server_active mysql8instance || true
if server_has_floating_ip mysql8instance; then
  log "Floating IP already assigned to mysql8instance; skipping."
else
  assign_floating_ip mysql8instance PUBLICNET
fi
wait_for_server_active sql || true
if server_has_floating_ip sql; then
  log "Floating IP already assigned to sql; skipping."
else
  assign_floating_ip sql PUBLICNET
fi
wait_for_server_active Mariadb || true
if server_has_floating_ip Mariadb; then
  log "Floating IP already assigned to Mariadb; skipping."
else
  assign_floating_ip Mariadb PUBLICNET
fi
wait_for_server_active hadbaas-vip-01 || true
if server_has_floating_ip hadbaas-vip-01; then
  log "Floating IP already assigned to hadbaas-vip-01; skipping."
else
  assign_floating_ip hadbaas-vip-01 PUBLICNET
fi
wait_for_server_active Instance-20 || true
if server_has_floating_ip Instance-20; then
  log "Floating IP already assigned to Instance-20; skipping."
else
  assign_floating_ip Instance-20 PUBLICNET
fi
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
phase_banner "PHASE 5: Load Balancer Creation — copies LB/Listener/Pool config from OSPC and wires server IPs as pool members (floating IPs not required)" "PHASE 6: Volume Attach next"
log "ℹ  Load balancer frontend- Load-Balancer-01 has no backend instance members; skipping member wiring."
lb_subnet_id=$(subnet_id_from_name tenant-subnet)
if [[ -n "$lb_subnet_id" ]]; then
  wait_for_server_active Alma9 || true
  member_ip=$(wait_for_instance_ip_on_network Alma9 tenant-net || true)
  if [[ -n "$member_ip" ]]; then
    if pool_has_member_ip u24backend-pool "$member_ip"; then
      echo "LB member already exists for $member_ip on u24backend-pool; skipping."
    else
      os loadbalancer member create --subnet-id "$lb_subnet_id" --address "$member_ip" --protocol-port 80 u24backend-pool || true
    fi
  else
    log "⚠  Could not resolve IP for Alma9 on tenant-net — instance may still be booting; skipping member."
  fi
fi
log "ℹ  Load balancer DB_loadbalancer MYSQL has no backend instance members; skipping member wiring."
log "ℹ  Load balancer LBmariaDB has no backend instance members; skipping member wiring."
log "ℹ  Load balancer perconaLB has no backend instance members; skipping member wiring."
phase_banner "PHASE 6: Volume Attachment — optional; skips automatically after ${MAX_VOL_ATTACH_TRIALS:-3} failed trials per pair"
MAX_VOL_ATTACH_TRIALS=${MAX_VOL_ATTACH_TRIALS:-3}  # override: MAX_VOL_ATTACH_TRIALS=5 bash <script>
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "SOURCE INFRA → TARGET FLEX DEPLOY SUMMARY"
log "Source elements planned: VMs=46 Volumes=63 LoadBalancers=5"
printf "| %-34s | %-24s | %-34s | %-18s | %-8s |\n" "Source VM" "Original Flavor" "Target FLEX VM" "FLEX Flavor" "Status"
printf "| %-34s | %-24s | %-34s | %-18s | %-8s |\n" "----------------------------------" "------------------------" "----------------------------------" "------------------" "--------"
_SUMMARY_VM_OK=0
_SUMMARY_VM_FAIL=0
if openstack server show Server-27 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" Server-27 - Server-27 gp.0.2.2 "$_VM_STATUS"
if openstack server show haproxyopsc >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" haproxyopsc - haproxyopsc gp.0.4.4 "$_VM_STATUS"
if openstack server show u24clean >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" u24clean - u24clean gp.0.2.2 "$_VM_STATUS"
if openstack server show debian12 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" debian12 - debian12 gp.0.2.2 "$_VM_STATUS"
if openstack server show 'u24 green server' >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" 'u24 green server' - 'u24 green server' gp.0.2.2 "$_VM_STATUS"
if openstack server show u-22 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" u-22 - u-22 gp.0.2.2 "$_VM_STATUS"
if openstack server show Server-21 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" Server-21 - Server-21 gp.0.2.2 "$_VM_STATUS"
if openstack server show musicradio >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" musicradio - musicradio gp.0.2.2 "$_VM_STATUS"
if openstack server show postgresqlU24 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" postgresqlU24 - postgresqlU24 gp.0.2.2 "$_VM_STATUS"
if openstack server show 'mongo db u24' >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" 'mongo db u24' - 'mongo db u24' gp.0.2.2 "$_VM_STATUS"
if openstack server show bigjumpwindowsiad >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" bigjumpwindowsiad - bigjumpwindowsiad gp.0.16.64 "$_VM_STATUS"
if openstack server show Bigjim-iad >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" Bigjim-iad - Bigjim-iad gp.0.16.64 "$_VM_STATUS"
if openstack server show jenkins >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" jenkins - jenkins gp.0.4.4 "$_VM_STATUS"
if openstack server show centos7 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" centos7 - centos7 gp.0.2.4 "$_VM_STATUS"
if openstack server show debian11new >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" debian11new - debian11new gp.0.2.2 "$_VM_STATUS"
if openstack server show dbian10new >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" dbian10new - dbian10new gp.0.2.2 "$_VM_STATUS"
if openstack server show u20 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" u20 - u20 gp.0.2.2 "$_VM_STATUS"
if openstack server show rocky9 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" rocky9 - rocky9 gp.0.2.2 "$_VM_STATUS"
if openstack server show alma8 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" alma8 - alma8 gp.0.2.4 "$_VM_STATUS"
if openstack server show dbian12 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" dbian12 - dbian12 gp.0.2.4 "$_VM_STATUS"
if openstack server show Alma9 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" Alma9 - Alma9 gp.0.4.8 "$_VM_STATUS"
if openstack server show rocky8 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" rocky8 - rocky8 gp.0.4.8 "$_VM_STATUS"
if openstack server show 'HA percona 8-02' >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" 'HA percona 8-02' - 'HA percona 8-02' gp.0.2.2 "$_VM_STATUS"
if openstack server show drupal >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" drupal - drupal gp.0.2.2 "$_VM_STATUS"
if openstack server show dbaasmariadb >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" dbaasmariadb - dbaasmariadb gp.0.2.2 "$_VM_STATUS"
if openstack server show HA-Mysql8-01 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" HA-Mysql8-01 - HA-Mysql8-01 gp.0.2.2 "$_VM_STATUS"
if openstack server show HA-mariaDB-02 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" HA-mariaDB-02 - HA-mariaDB-02 gp.0.2.2 "$_VM_STATUS"
if openstack server show drupalphp_Database >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" drupalphp_Database - drupalphp_Database gp.0.2.2 "$_VM_STATUS"
if openstack server show 'HA percona 8-03' >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" 'HA percona 8-03' - 'HA percona 8-03' gp.0.2.2 "$_VM_STATUS"
if openstack server show HA-mariaDB-03 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" HA-mariaDB-03 - HA-mariaDB-03 gp.0.2.2 "$_VM_STATUS"
if openstack server show lamp_Database >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" lamp_Database - lamp_Database gp.0.2.2 "$_VM_STATUS"
if openstack server show HAdbaasSql-03 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" HAdbaasSql-03 - HAdbaasSql-03 gp.0.2.2 "$_VM_STATUS"
if openstack server show Stack-05_Database >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" Stack-05_Database - Stack-05_Database gp.0.2.2 "$_VM_STATUS"
if openstack server show HAmysql-01 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" HAmysql-01 - HAmysql-01 gp.0.2.2 "$_VM_STATUS"
if openstack server show mariad1 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" mariad1 - mariad1 gp.0.2.2 "$_VM_STATUS"
if openstack server show hadbaas-vip-03 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" hadbaas-vip-03 - hadbaas-vip-03 gp.0.2.2 "$_VM_STATUS"
if openstack server show Instance-21 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" Instance-21 - Instance-21 gp.0.2.2 "$_VM_STATUS"
if openstack server show mysql8instance >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" mysql8instance - mysql8instance gp.0.2.2 "$_VM_STATUS"
if openstack server show sql >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" sql - sql gp.0.2.2 "$_VM_STATUS"
if openstack server show Mariadb >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" Mariadb - Mariadb gp.0.2.2 "$_VM_STATUS"
if openstack server show hadbaas-vip-01 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" hadbaas-vip-01 - hadbaas-vip-01 gp.0.2.2 "$_VM_STATUS"
if openstack server show Instance-20 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" Instance-20 - Instance-20 gp.0.2.2 "$_VM_STATUS"
if openstack server show ospcwin2019 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" ospcwin2019 - ospcwin2019 gp.0.2.4 "$_VM_STATUS"
if openstack server show opscwin2016 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" opscwin2016 - opscwin2016 gp.0.2.4 "$_VM_STATUS"
if openstack server show win2019 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" win2019 - win2019 gp.0.2.4 "$_VM_STATUS"
if openstack server show windows2016 >/dev/null 2>&1; then _VM_STATUS='created'; _SUMMARY_VM_OK=$((_SUMMARY_VM_OK + 1)); else _VM_STATUS='failed'; _SUMMARY_VM_FAIL=$((_SUMMARY_VM_FAIL + 1)); fi
printf "| %-34.34s | %-24.24s | %-34.34s | %-18.18s | %-8s |\n" windows2016 - windows2016 gp.0.2.4 "$_VM_STATUS"
log "Target FLEX VM count: $_SUMMARY_VM_OK created/reused, $_SUMMARY_VM_FAIL failed, total planned: 46"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Write per-run rollback script before summary
_finalize_rollback

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "✅  DEPLOY COMPLETE at $(date)"
log "   Resources created  : $DEPLOY_CREATED"
log "   Resources skipped  : $DEPLOY_SKIPPED (already existed)"
log "   Tasks timed out    : $DEPLOY_TIMEOUTS (skipped after 30s — re-run or handle manually)"
log "   Errors encountered : $DEPLOY_ERRORS"
if (( DEPLOY_TIMEOUTS > 0 )); then
  warn "  ⏭  $DEPLOY_TIMEOUTS task(s) exceeded the 30s timeout and were skipped"
  warn "     Override limit:  OS_CMD_TIMEOUT_SEC=120 bash <script>"
  warn "     Re-run specific phases by setting RESOURCE_COLLISION_POLICY=reuse"
fi
log ""
log "NEXT STEPS"
log "  1. Verify instances and assigned FIPs: openstack server list"
log "  2. Verify LBs:       openstack loadbalancer list"
log "  3. Verify volumes:   openstack volume list"
log "  4. If LB VIPs need public access, assign LB floating IPs manually."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
