#!/usr/bin/env bash
# Generated by OSPC→FLEX Deployer — do NOT edit by hand.
# Floating IP association is intentionally SKIPPED — assign manually after deploy.
set -uo pipefail

# ── Runtime config (override from environment before running) ──────────────
SERVER_WAIT_SEC="${SERVER_WAIT_SEC:-600}"       # 10 min per server active-wait
VOLUME_WAIT_SEC="${VOLUME_WAIT_SEC:-300}"       # 5 min per volume available-wait
LB_WAIT_SEC="${LB_WAIT_SEC:-480}"               # 8 min per LB active-wait
OS_CMD_TIMEOUT_SEC="${OS_CMD_TIMEOUT_SEC:-30}"  # 30s per API call — skip if exceeded
RESOURCE_COLLISION_POLICY="${RESOURCE_COLLISION_POLICY:-reuse}"
ROLLBACK_AUTO_APPROVE=1                          # never prompt; rollback always runs
ROLLBACK_SCRIPT_PATH="${ROLLBACK_SCRIPT_PATH:-/home/dzoan/OSPC2FLEX/osflex-deployer-fullmig-3.0/uploads/last_rollback_$(date +%Y%m%d_%H%M%S).sh}"
DEPLOY_ERRORS=0
DEPLOY_SKIPPED=0
DEPLOY_CREATED=0
DEPLOY_TIMEOUTS=0
_ROLLBACK_CMDS=()   # populated at runtime; only resources CREATED (not reused) are added

# ── Timestamped logging ──────────────────────────────────────────────────────
log()  { echo "[$(date '+%H:%M:%S')] $*"; }
warn() { echo "[$(date '+%H:%M:%S')] ⚠  $*" >&2; }
err()  { echo "[$(date '+%H:%M:%S')] ✖  $*" >&2; DEPLOY_ERRORS=$((DEPLOY_ERRORS+1)); }
ok()   { echo "[$(date '+%H:%M:%S')] ✔  $*"; DEPLOY_CREATED=$((DEPLOY_CREATED+1)); }
skip() { echo "[$(date '+%H:%M:%S')] ↩  $*"; DEPLOY_SKIPPED=$((DEPLOY_SKIPPED+1)); }

phase_banner() {
  local msg="$1"
  local next="${2:-}"
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  log "🚀  $msg"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  if [[ -n "$next" ]]; then
    log "   NEXT STEP: $next"
  fi
}

# ── Guarded openstack wrapper ─────────────────────────────────────────────────
run_with_timeout() {
  local timeout_sec="$1"
  shift
  "$@" &
  local pid=$!
  local start_ts elapsed
  start_ts=$(date +%s)
  while kill -0 "$pid" 2>/dev/null; do
    elapsed=$(( $(date +%s) - start_ts ))
    if (( elapsed >= timeout_sec )); then
      warn "⏭  TIMEOUT ${timeout_sec}s — SKIPPING task and continuing deploy: $*"
      kill -TERM "$pid" 2>/dev/null || true; sleep 1
      kill -KILL "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
      DEPLOY_TIMEOUTS=$((DEPLOY_TIMEOUTS+1))
      return 0   # skip — do NOT block the rest of the deploy
    fi
    sleep 1
  done
  wait "$pid"
}

os() {
  log "+ openstack $*"
  run_with_timeout "$OS_CMD_TIMEOUT_SEC" openstack "$@"
}

# ── Resource idempotency ──────────────────────────────────────────────────────
resource_exists() {
  local kind="$1" name="$2"
  case "$kind" in
    network)       openstack network show "$name" >/dev/null 2>&1 ;;
    subnet)        openstack subnet show "$name" >/dev/null 2>&1 ;;
    router)        openstack router show "$name" >/dev/null 2>&1 ;;
    security_group) openstack security group show "$name" >/dev/null 2>&1 ;;
    instance)      openstack server show "$name" >/dev/null 2>&1 ;;
    volume)        openstack volume show "$name" >/dev/null 2>&1 ;;
    load_balancer) openstack loadbalancer show "$name" >/dev/null 2>&1 ;;
    listener)      openstack loadbalancer listener show "$name" >/dev/null 2>&1 ;;
    pool)          openstack loadbalancer pool show "$name" >/dev/null 2>&1 ;;
    *) return 1 ;;
  esac
}

create_or_reuse() {
  local kind="$1" name="$2"
  shift 2
  if resource_exists "$kind" "$name"; then
    if [[ "$RESOURCE_COLLISION_POLICY" == "fail" ]]; then
      err "BLOCKER: $kind '$name' already exists and RESOURCE_COLLISION_POLICY=fail"
      return 1
    fi
    skip "Already exists — reusing $kind: $name"
    return 0
  fi
  log "Creating $kind: $name ..."
  if "$@"; then
    ok "Created $kind: $name"
    _rollback_push "$kind" "$name"
  else
    err "FAILED to create $kind: $name — check output above for reason"
    if [[ "$kind" == "instance" ]]; then
      warn "  Common blockers for instances:"
      warn "    • Flavor disk too small for image (check 'minimum_disk' in image metadata)"
      warn "    • Quota exceeded (check 'openstack quota show')"
      warn "    • Network not reachable (check phase 1 succeeded)"
      warn "    • Key pair does not exist in project"
    fi
  fi
}

# ── Per-run rollback tracker (only NEW resources, not pre-existing ones) ─────
_rollback_push() {
  local kind="$1" name="$2" cmd
  case "$kind" in
    network)        cmd="openstack network delete \"$name\" || true" ;;
    subnet)         cmd="openstack subnet delete \"$name\" || true" ;;
    router)         cmd="openstack router remove subnet \"$name\" \"${SUBNET_NAME:-tenant-subnet}\" || true; openstack router unset --external-gateway \"$name\" || true; openstack router delete \"$name\" || true" ;;
    security_group) cmd="openstack security group delete \"$name\" || true" ;;
    instance)       cmd="openstack server delete --wait \"$name\" 2>/dev/null || openstack server delete \"$name\" || true" ;;
    volume)         cmd="openstack volume delete --force \"$name\" || true" ;;
    load_balancer)  cmd="openstack loadbalancer delete --cascade \"$name\" 2>/dev/null || openstack loadbalancer delete \"$name\" || true" ;;
    listener|pool)  return 0 ;;
    *)              return 0 ;;
  esac
  _ROLLBACK_CMDS=("$cmd" "${_ROLLBACK_CMDS[@]+${_ROLLBACK_CMDS[@]}}")
}

_finalize_rollback() {
  [[ ${#_ROLLBACK_CMDS[@]} -eq 0 ]] && { warn "No new resources created — rollback script skipped."; return 0; }
  local n=${#_ROLLBACK_CMDS[@]} i
  {
    echo '#!/usr/bin/env bash'
    echo '# AUTO-GENERATED rollback — deletes ONLY resources created in THIS run.'
    echo '# Pre-existing (reused) resources are NOT touched.'
    echo 'set -uo pipefail'
    echo 'ROLLBACK_AUTO_APPROVE=1'
    echo 'log() { echo "[$(date +%H:%M:%S)] $*"; }'
    printf "log \"Starting rollback: $n step(s) in reverse creation order\"\n"
    for (( i=0; i<n; i++ )); do
      printf "log \"  [%d/%d] %s\"\n" "$((i+1))" "$n" "${_ROLLBACK_CMDS[$i]}"
      printf "%s\n" "${_ROLLBACK_CMDS[$i]}"
    done
    echo 'log "✅  Rollback complete."'
  } > "$ROLLBACK_SCRIPT_PATH"
  chmod +x "$ROLLBACK_SCRIPT_PATH"
  log "↩  Rollback script written: $ROLLBACK_SCRIPT_PATH ($n steps)"
}

# ── Wait helpers (with live progress output) ──────────────────────────────────
wait_for_server_active() {
  local name="$1"
  local max_sec="${2:-$SERVER_WAIT_SEC}"
  local sleep_sec=10
  local elapsed=0 status fault
  log "⏳ Waiting for server '$name' to become ACTIVE (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack server show "$name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "ACTIVE" ]]; then
      ok "Server '$name' is ACTIVE (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "ERROR" ]]; then
      fault=$(openstack server show "$name" -f value -c fault 2>/dev/null || echo "unknown fault")
      err "BLOCKER: Server '$name' entered ERROR state after ${elapsed}s"
      err "  Fault details: $fault"
      warn "  Common causes:"
      warn "    • Flavor disk smaller than image minimum_disk — use --boot-from-volume"
      warn "    • Host capacity insufficient — try a different availability zone"
      warn "    • Image not found or inaccessible in this region"
      warn "  NEXT STEP: Delete the error server and re-create with a larger flavor or boot-from-volume"
      return 1
    fi
    log "  ... server '$name' status=$status  elapsed=${elapsed}s / ${max_sec}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Server '$name' did not reach ACTIVE after ${max_sec}s (last status: $status)"
  warn "  NEXT STEP: Check 'openstack server show $name' — if still BUILD, try waiting longer"
  warn "            If ERROR, see fault reason above and re-create with corrected params"
  return 1
}

wait_for_volume_available() {
  local name="$1"
  local max_sec="${2:-$VOLUME_WAIT_SEC}"
  local sleep_sec=5
  local elapsed=0 status
  log "⏳ Waiting for volume '$name' to become available (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack volume show "$name" -f value -c status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "available" ]]; then
      ok "Volume '$name' is available (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "error" ]]; then
      err "BLOCKER: Volume '$name' entered error state after ${elapsed}s"
      warn "  NEXT STEP: Delete the volume and re-create, or check Cinder quota"
      return 1
    fi
    log "  ... volume '$name' status=$status  elapsed=${elapsed}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Volume '$name' not available after ${max_sec}s"
  return 1
}

volume_status() {
  local name="$1"
  openstack volume show "$name" -f value -c status 2>/dev/null || true
}

server_has_volume() {
  local server_name="$1" volume_name="$2" volume_id
  volume_id=$(openstack volume show "$volume_name" -f value -c id 2>/dev/null || true)
  [[ -n "$volume_id" ]] && openstack server volume list "$server_name" -f value -c ID 2>/dev/null | grep -Fx "$volume_id" >/dev/null 2>&1
}

wait_for_loadbalancer_active() {
  local name="$1"
  local max_sec="${2:-$LB_WAIT_SEC}"
  local sleep_sec=10
  local elapsed=0 status
  log "⏳ Waiting for load balancer '$name' to become ACTIVE (timeout: ${max_sec}s) ..."
  while (( elapsed < max_sec )); do
    status=$(openstack loadbalancer show "$name" -f value -c provisioning_status 2>/dev/null || echo "UNKNOWN")
    if [[ "$status" == "ACTIVE" ]]; then
      ok "Load balancer '$name' is ACTIVE (elapsed: ${elapsed}s)"
      return 0
    fi
    if [[ "$status" == "ERROR" ]]; then
      err "BLOCKER: Load balancer '$name' provisioning ERROR after ${elapsed}s"
      warn "  NEXT STEP: 'openstack loadbalancer show $name' for operating_status details"
      return 1
    fi
    log "  ... LB '$name' provisioning_status=$status  elapsed=${elapsed}s / ${max_sec}s"
    sleep "$sleep_sec"
    elapsed=$((elapsed + sleep_sec))
  done
  err "TIMEOUT: Load balancer '$name' did not reach ACTIVE after ${max_sec}s"
  return 1
}

subnet_id_from_name() {
  openstack subnet show "$1" -f value -c id 2>/dev/null || true
}

instance_ip_on_network() {
  local server_name="$1" network_name="$2" ports_line ip line
  ports_line=$(openstack port list --server "$server_name" --network "$network_name" -f value -c "Fixed IP Addresses" 2>/dev/null | head -n 1 || true)
  if [[ -n "$ports_line" ]]; then
    ip=$(echo "$ports_line" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | head -n 1 || true)
    [[ -n "$ip" ]] && { echo "$ip"; return 0; }
  fi
  line=$(openstack server show "$server_name" -f value -c addresses 2>/dev/null | tr "," "\n" | sed "s/^ *//g" | grep "^${network_name}=" | head -n 1 || true)
  [[ -z "$line" ]] && return 0
  ip=$(echo "$line" | sed -E 's/^[^=]+=([0-9.]+).*/\1/g')
  echo "$ip"
}

wait_for_instance_ip_on_network() {
  local server_name="$1" network_name="$2"
  local max_sec="${3:-120}" sleep_sec=5
  local elapsed=0 ip
  log "⏳ Waiting for IP on network '$network_name' for server '$server_name' ..."
  while (( elapsed < max_sec )); do
    ip=$(instance_ip_on_network "$server_name" "$network_name")
    if [[ -n "$ip" ]]; then
      log "  IP resolved: $server_name → $ip"
      echo "$ip"; return 0
    fi
    sleep "$sleep_sec"; elapsed=$((elapsed + sleep_sec))
  done
  warn "Could not resolve IP for $server_name on $network_name after ${max_sec}s"
  return 1
}

pool_has_member_ip() {
  openstack loadbalancer member list "$1" -f value -c address 2>/dev/null | grep -Fx "$2" >/dev/null 2>&1
}

loadbalancer_vip_port_id() {
  openstack loadbalancer show "$1" -f value -c vip_port_id 2>/dev/null || true
}

# NOTE: Floating IP helpers kept for reference but are NOT called by this script.
# Floating IPs are assigned MANUALLY after deployment completes.
server_has_floating_ip() {
  local out; out=$(openstack floating ip list --server "$1" -f value -c "Floating IP Address" 2>/dev/null || true)
  [[ -n "$(echo "$out" | tr -d "[:space:]")" ]]
}

port_has_floating_ip() {
  local out; out=$(openstack floating ip list --port "$1" -f value -c "Floating IP Address" 2>/dev/null || true)
  [[ -n "$(echo "$out" | tr -d "[:space:]")" ]]
}

log "Deploy script started at $(date)"
log "Floating IP assignment: SKIPPED (assign manually via Horizon or CLI after deploy)"
log "Server wait timeout   : ${SERVER_WAIT_SEC}s"
log "LB wait timeout       : ${LB_WAIT_SEC}s"
log "Collision policy      : ${RESOURCE_COLLISION_POLICY}"

phase_banner "PHASE 4: Compute — Windows VMs fired in background first (sysprep is slow), Linux VMs inline" "PHASE 5: Volume Attach after all VMs are ACTIVE"
echo "  -> Firing Windows VMs in background (sysprep takes longest)..."
_WIN_PIDS=()
( # Windows VM: Windows Server 2019Re
create_or_reuse instance 'Windows Server 2019Re' os server create --flavor gp.5.2.4 --image 'Windows Server 2019' --network tenant-net --security-group default --password TZw7zozjcNzsLf 'Windows Server 2019Re'
) &
_WIN_PIDS+=($!)
( # Windows VM: win2019websql2019
create_or_reuse instance win2019websql2019 os server create --flavor gp.5.2.4 --image 'Windows Server 2019 with SQL 2019 Web' --network tenant-net --security-group default --password vLnpAdvuW4pbFT win2019websql2019
) &
_WIN_PIDS+=($!)
( # Windows VM: Windows Server 2016 + SQL Server 2019
create_or_reuse instance 'Windows Server 2016 + SQL Server 2019' os server create --flavor gp.5.2.4 --image 'Windows Server 2016' --network tenant-net --security-group default --password J7bdIlvjGrUjpQ 'Windows Server 2016 + SQL Server 2019'
) &
_WIN_PIDS+=($!)
echo "  -> Provisioning Linux VMs..."
create_or_reuse instance ospc-jumpHost os server create --flavor gp.5.2.2 --image 'Ubuntu 24.04' --network tenant-net --security-group default --key-name laptopubuntu24 ospc-jumpHost
create_or_reuse instance u24-postgresl os server create --flavor gp.5.2.2 --image 'Ubuntu 24.04' --network tenant-net --security-group default --key-name laptopubuntu24 u24-postgresl
create_or_reuse instance u24-FrontEnd os server create --flavor gp.5.2.2 --image 'Ubuntu 24.04' --network tenant-net --security-group default --key-name laptopubuntu24 u24-FrontEnd
create_or_reuse instance php-ospc os server create --flavor gp.5.4.4 --image 'Rocky Linux 8' --network tenant-net --security-group default --key-name laptopubuntu24 php-ospc
create_or_reuse instance u24Backend os server create --flavor gp.5.2.2 --image 'Ubuntu 24.04' --network tenant-net --security-group default --key-name laptopubuntu24 u24Backend
create_or_reuse instance 'HA percona 8-02' os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 'HA percona 8-02'
create_or_reuse instance drupal os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 drupal
create_or_reuse instance HA-Mysql8-01 os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 HA-Mysql8-01
create_or_reuse instance HA-mariaDB-02 os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 HA-mariaDB-02
create_or_reuse instance php-ospc_Database os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 php-ospc_Database
create_or_reuse instance 'HA percona 8-03' os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 'HA percona 8-03'
create_or_reuse instance HA-mariaDB-03 os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 HA-mariaDB-03
create_or_reuse instance Stack-05_Database os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 Stack-05_Database
create_or_reuse instance sql os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 sql
create_or_reuse instance HA-Mysql8-02 os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 HA-Mysql8-02
create_or_reuse instance HA-mariaDB-01 os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 HA-mariaDB-01
create_or_reuse instance Instance-05-03 os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 Instance-05-03
create_or_reuse instance 'HA percona 8-01' os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 'HA percona 8-01'
create_or_reuse instance Instance-05-02 os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 Instance-05-02
create_or_reuse instance HA-Mysql8-03 os server create --flavor gp.5.2.2 --image 'Ubuntu 22.04' --network tenant-net --security-group default --key-name laptopubuntu24 HA-Mysql8-03
echo "  -> Waiting for Windows VMs to finish provisioning..."
for _wpid in "${_WIN_PIDS[@]}"; do wait "$_wpid" || true; done
echo "  -> All Windows VMs provisioning complete."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "⚠  FLOATING IP ASSIGNMENT: SKIPPED (manual action required)"
log "   Assign Floating IPs manually via Horizon or CLI after deploy:"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip 'Windows Server 2019Re' <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip win2019websql2019 <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip 'Windows Server 2016 + SQL Server 2019' <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip ospc-jumpHost <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip u24-postgresl <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip u24-FrontEnd <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip php-ospc <FIP>"
log "     openstack floating ip create PUBLICNET | then: openstack server add floating ip u24Backend <FIP>"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
phase_banner "PHASE 5: Volume Attachment — attach pre-created volumes to running instances" "PHASE 6: LB Member Wiring next"
wait_for_server_active u24-postgresl || true
if server_has_volume u24-postgresl data-windows-server-2016-sql-server-2019-1; then
  echo "Volume data-windows-server-2016-sql-server-2019-1 is already attached to u24-postgresl; skipping."
else
  vol_status=$(volume_status data-windows-server-2016-sql-server-2019-1)
  if [[ "$vol_status" == "available" ]]; then
    os server add volume u24-postgresl data-windows-server-2016-sql-server-2019-1 || true
  elif [[ "$vol_status" == "in-use" ]]; then
    echo "Volume data-windows-server-2016-sql-server-2019-1 is in-use and not attached to u24-postgresl; skipping." >&2
  else
    wait_for_volume_available data-windows-server-2016-sql-server-2019-1 || true
    os server add volume u24-postgresl data-windows-server-2016-sql-server-2019-1 || true
  fi
fi
wait_for_server_active u24-FrontEnd || true
if server_has_volume u24-FrontEnd data-windows-server-2016-sql-server-2019-1; then
  echo "Volume data-windows-server-2016-sql-server-2019-1 is already attached to u24-FrontEnd; skipping."
else
  vol_status=$(volume_status data-windows-server-2016-sql-server-2019-1)
  if [[ "$vol_status" == "available" ]]; then
    os server add volume u24-FrontEnd data-windows-server-2016-sql-server-2019-1 || true
  elif [[ "$vol_status" == "in-use" ]]; then
    echo "Volume data-windows-server-2016-sql-server-2019-1 is in-use and not attached to u24-FrontEnd; skipping." >&2
  else
    wait_for_volume_available data-windows-server-2016-sql-server-2019-1 || true
    os server add volume u24-FrontEnd data-windows-server-2016-sql-server-2019-1 || true
  fi
fi
wait_for_server_active 'Windows Server 2019Re' || true
if server_has_volume 'Windows Server 2019Re' data-windows-server-2016-sql-server-2019-1; then
  echo "Volume data-windows-server-2016-sql-server-2019-1 is already attached to Windows Server 2019Re; skipping."
else
  vol_status=$(volume_status data-windows-server-2016-sql-server-2019-1)
  if [[ "$vol_status" == "available" ]]; then
    os server add volume 'Windows Server 2019Re' data-windows-server-2016-sql-server-2019-1 || true
  elif [[ "$vol_status" == "in-use" ]]; then
    echo "Volume data-windows-server-2016-sql-server-2019-1 is in-use and not attached to Windows Server 2019Re; skipping." >&2
  else
    wait_for_volume_available data-windows-server-2016-sql-server-2019-1 || true
    os server add volume 'Windows Server 2019Re' data-windows-server-2016-sql-server-2019-1 || true
  fi
fi
wait_for_server_active win2019websql2019 || true
if server_has_volume win2019websql2019 data-windows-server-2016-sql-server-2019-1; then
  echo "Volume data-windows-server-2016-sql-server-2019-1 is already attached to win2019websql2019; skipping."
else
  vol_status=$(volume_status data-windows-server-2016-sql-server-2019-1)
  if [[ "$vol_status" == "available" ]]; then
    os server add volume win2019websql2019 data-windows-server-2016-sql-server-2019-1 || true
  elif [[ "$vol_status" == "in-use" ]]; then
    echo "Volume data-windows-server-2016-sql-server-2019-1 is in-use and not attached to win2019websql2019; skipping." >&2
  else
    wait_for_volume_available data-windows-server-2016-sql-server-2019-1 || true
    os server add volume win2019websql2019 data-windows-server-2016-sql-server-2019-1 || true
  fi
fi
wait_for_server_active 'Windows Server 2016 + SQL Server 2019' || true
if server_has_volume 'Windows Server 2016 + SQL Server 2019' data-windows-server-2016-sql-server-2019-1; then
  echo "Volume data-windows-server-2016-sql-server-2019-1 is already attached to Windows Server 2016 + SQL Server 2019; skipping."
else
  vol_status=$(volume_status data-windows-server-2016-sql-server-2019-1)
  if [[ "$vol_status" == "available" ]]; then
    os server add volume 'Windows Server 2016 + SQL Server 2019' data-windows-server-2016-sql-server-2019-1 || true
  elif [[ "$vol_status" == "in-use" ]]; then
    echo "Volume data-windows-server-2016-sql-server-2019-1 is in-use and not attached to Windows Server 2016 + SQL Server 2019; skipping." >&2
  else
    wait_for_volume_available data-windows-server-2016-sql-server-2019-1 || true
    os server add volume 'Windows Server 2016 + SQL Server 2019' data-windows-server-2016-sql-server-2019-1 || true
  fi
fi

# Write per-run rollback script before summary
_finalize_rollback

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "✅  DEPLOY COMPLETE at $(date)"
log "   Resources created  : $DEPLOY_CREATED"
log "   Resources skipped  : $DEPLOY_SKIPPED (already existed)"
log "   Tasks timed out    : $DEPLOY_TIMEOUTS (skipped after 30s — re-run or handle manually)"
log "   Errors encountered : $DEPLOY_ERRORS"
if (( DEPLOY_TIMEOUTS > 0 )); then
  warn "  ⏭  $DEPLOY_TIMEOUTS task(s) exceeded the 30s timeout and were skipped"
  warn "     Override limit:  OS_CMD_TIMEOUT_SEC=120 bash <script>"
  warn "     Re-run specific phases by setting RESOURCE_COLLISION_POLICY=reuse"
fi
log ""
log "NEXT STEPS (manual)"
log "  1. Assign Floating IPs to VMs and LB VIPs via Horizon or:"
log "       openstack floating ip create PUBLICNET"
log "       openstack server add floating ip <server> <fip>"
log "  2. Verify instances: openstack server list"
log "  3. Verify LBs:       openstack loadbalancer list"
log "  4. Verify volumes:   openstack volume list"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
